// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgresdriver

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pokt-foundation/portal-db/v2/types"
)

type AuthProvider string

const (
	AuthProviderAuth0 AuthProvider = "auth0"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type AuthType string

const (
	AuthTypeAuth0Github   AuthType = "auth0_github"
	AuthTypeAuth0Username AuthType = "auth0_username"
)

func (e *AuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthType(s)
	case string:
		*e = AuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthType: %T", src)
	}
	return nil
}

type NullAuthType struct {
	AuthType AuthType `json:"auth_type"`
	Valid    bool     `json:"valid"` // Valid is true if AuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthType), nil
}

type ChainAuthType string

const (
	ChainAuthTypeBasicAuth   ChainAuthType = "basic_auth"
	ChainAuthTypeBearerToken ChainAuthType = "bearer_token"
	ChainAuthTypeNone        ChainAuthType = "none"
)

func (e *ChainAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainAuthType(s)
	case string:
		*e = ChainAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainAuthType: %T", src)
	}
	return nil
}

type NullChainAuthType struct {
	ChainAuthType ChainAuthType `json:"chain_auth_type"`
	Valid         bool          `json:"valid"` // Valid is true if ChainAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.ChainAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainAuthType), nil
}

type ChainCheckType string

const (
	ChainCheckTypeArchival ChainCheckType = "archival"
	ChainCheckTypeChain    ChainCheckType = "chain"
	ChainCheckTypeMerge    ChainCheckType = "merge"
	ChainCheckTypeSync     ChainCheckType = "sync"
)

func (e *ChainCheckType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainCheckType(s)
	case string:
		*e = ChainCheckType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainCheckType: %T", src)
	}
	return nil
}

type NullChainCheckType struct {
	ChainCheckType ChainCheckType `json:"chain_check_type"`
	Valid          bool           `json:"valid"` // Valid is true if ChainCheckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainCheckType) Scan(value interface{}) error {
	if value == nil {
		ns.ChainCheckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainCheckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainCheckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainCheckType), nil
}

type Environment string

const (
	EnvironmentProduction Environment = "production"
	EnvironmentTest       Environment = "test"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment `json:"environment"`
	Valid       bool        `json:"valid"` // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type NotificationEvent string

const (
	NotificationEventFull          NotificationEvent = "full"
	NotificationEventHalf          NotificationEvent = "half"
	NotificationEventQuarter       NotificationEvent = "quarter"
	NotificationEventSignedUp      NotificationEvent = "signedUp"
	NotificationEventThreeQuarters NotificationEvent = "threeQuarters"
)

func (e *NotificationEvent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationEvent(s)
	case string:
		*e = NotificationEvent(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationEvent: %T", src)
	}
	return nil
}

type NullNotificationEvent struct {
	NotificationEvent NotificationEvent `json:"notification_event"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationEvent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationEvent) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationEvent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationEvent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationEvent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationEvent), nil
}

type NotificationType string

const (
	NotificationTypeEmail   NotificationType = "email"
	NotificationTypePortal  NotificationType = "portal"
	NotificationTypeWebhook NotificationType = "webhook"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Permissions string

const (
	PermissionsReadEndpoint     Permissions = "read:endpoint"
	PermissionsWriteEndpoint    Permissions = "write:endpoint"
	PermissionsDeleteEndpoint   Permissions = "delete:endpoint"
	PermissionsTransferEndpoint Permissions = "transfer:endpoint"
)

func (e *Permissions) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Permissions(s)
	case string:
		*e = Permissions(s)
	default:
		return fmt.Errorf("unsupported scan type for Permissions: %T", src)
	}
	return nil
}

type NullPermissions struct {
	Permissions Permissions `json:"permissions"`
	Valid       bool        `json:"valid"` // Valid is true if Permissions is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissions) Scan(value interface{}) error {
	if value == nil {
		ns.Permissions, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Permissions.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissions) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Permissions), nil
}

type WhitelistType string

const (
	WhitelistTypeBlockchains WhitelistType = "blockchains"
	WhitelistTypeContracts   WhitelistType = "contracts"
	WhitelistTypeMethods     WhitelistType = "methods"
	WhitelistTypeOrigins     WhitelistType = "origins"
	WhitelistTypeUserAgents  WhitelistType = "userAgents"
)

func (e *WhitelistType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhitelistType(s)
	case string:
		*e = WhitelistType(s)
	default:
		return fmt.Errorf("unsupported scan type for WhitelistType: %T", src)
	}
	return nil
}

type NullWhitelistType struct {
	WhitelistType WhitelistType `json:"whitelist_type"`
	Valid         bool          `json:"valid"` // Valid is true if WhitelistType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhitelistType) Scan(value interface{}) error {
	if value == nil {
		ns.WhitelistType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhitelistType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhitelistType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhitelistType), nil
}

type Account struct {
	ID                      types.AccountID    `json:"id"`
	Name                    pgtype.Text        `json:"name"`
	IconURL                 pgtype.Text        `json:"icon_url"`
	PlanType                pgtype.Text        `json:"plan_type"`
	PartnerChainIDs         []string           `json:"partner_chain_ids"`
	PartnerThroughputLimit  pgtype.Int4        `json:"partner_throughput_limit"`
	PartnerApplicationLimit pgtype.Int4        `json:"partner_application_limit"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Deleted                 bool               `json:"deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type AccountIntegration struct {
	ID                 int32              `json:"id"`
	AccountID          types.AccountID    `json:"account_id"`
	CovalentAPIKeyFree pgtype.Text        `json:"covalent_api_key_free"`
	CovalentAPIKeyPaid pgtype.Text        `json:"covalent_api_key_paid"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AccountUserAccess struct {
	ID                  int32              `json:"id"`
	UserID              types.UserID       `json:"user_id"`
	AccountID           types.AccountID    `json:"account_id"`
	PortalApplicationID types.PortalAppID  `json:"portal_application_id"`
	RoleName            types.RoleName     `json:"role_name"`
	Owner               bool               `json:"owner"`
	Accepted            bool               `json:"accepted"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Chain struct {
	ID             types.RelayChainID `json:"id"`
	Blockchain     pgtype.Text        `json:"blockchain"`
	Description    pgtype.Text        `json:"description"`
	EnforceResult  pgtype.Text        `json:"enforce_result"`
	Ticker         pgtype.Text        `json:"ticker"`
	Path           pgtype.Text        `json:"path"`
	IconURL        pgtype.Text        `json:"icon_url"`
	RequestTimeout pgtype.Int4        `json:"request_timeout"`
	LogLimitBlocks pgtype.Int4        `json:"log_limit_blocks"`
	AllowedMethods []string           `json:"allowed_methods"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Deleted        pgtype.Bool        `json:"deleted"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ChainAlias struct {
	ChainID   types.RelayChainID `json:"chain_id"`
	Alias     types.ChainAlias   `json:"alias"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChainAliasDomain struct {
	ChainID   types.RelayChainID `json:"chain_id"`
	Alias     types.ChainAlias   `json:"alias"`
	Domains   []string           `json:"domains"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ChainAltruist struct {
	ID        int32               `json:"id"`
	ChainID   types.RelayChainID  `json:"chain_id"`
	URL       types.AltruistURL   `json:"url"`
	Auth      pgtype.Text         `json:"auth"`
	AuthType  types.ChainAuthType `json:"auth_type"`
	CreatedAt pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt pgtype.Timestamptz  `json:"updated_at"`
}

type ChainCheck struct {
	ID         int32                `json:"id"`
	ChainID    types.RelayChainID   `json:"chain_id"`
	Type       types.ChainCheckType `json:"type"`
	Payload    pgtype.Text          `json:"payload"`
	ResultKey  pgtype.Text          `json:"result_key"`
	Allowance  pgtype.Int4          `json:"allowance"`
	EVMChainID pgtype.Int4          `json:"evm_chain_id"`
	CreatedAt  pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz   `json:"updated_at"`
}

type ChainsGigastakeApplication struct {
	ChainID                types.RelayChainID   `json:"chain_id"`
	GigastakeApplicationID types.GigastakeAppID `json:"gigastake_application_id"`
}

type GigastakeApplication struct {
	ID              types.GigastakeAppID `json:"id"`
	Name            string               `json:"name"`
	Address         string               `json:"address"`
	PublicKey       string               `json:"public_key"`
	ClientPublicKey string               `json:"client_public_key"`
	Signature       string               `json:"signature"`
	Version         string               `json:"version"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
	Deleted         bool                 `json:"deleted"`
	DeletedAt       pgtype.Timestamptz   `json:"deleted_at"`
}

type GlobalBlockedContract struct {
	ID             int32                `json:"id"`
	BlockedAddress types.BlockedAddress `json:"blocked_address"`
	Active         bool                 `json:"active"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `json:"updated_at"`
}

type PayPlan struct {
	Name              pgtype.Text        `json:"name"`
	Description       pgtype.Text        `json:"description"`
	PlanType          types.PayPlanType  `json:"plan_type"`
	ChainIDs          []string           `json:"chain_ids"`
	MonthlyRelayLimit int32              `json:"monthly_relay_limit"`
	ThroughputLimit   int32              `json:"throughput_limit"`
	ApplicationLimit  int32              `json:"application_limit"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DailyLimit        pgtype.Int4        `json:"daily_limit"`
}

type PortalApplication struct {
	ID                   types.PortalAppID  `json:"id"`
	AccountID            pgtype.Text        `json:"account_id"`
	Name                 string             `json:"name"`
	AppEmoji             pgtype.Text        `json:"app_emoji"`
	Description          pgtype.Text        `json:"description"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Deleted              bool               `json:"deleted"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	RequestTimeout       pgtype.Int4        `json:"request_timeout"`
	FirstDateSurpassed   pgtype.Timestamptz `json:"first_date_surpassed"`
	PlanType             types.PayPlanType  `json:"plan_type"`
	DailyLimit           pgtype.Int4        `json:"daily_limit"`
	CustomLimit          pgtype.Int4        `json:"custom_limit"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
}

type PortalApplicationAat struct {
	ID                  types.ProtocolAppID      `json:"id"`
	PortalApplicationID types.PortalAppID        `json:"portal_application_id"`
	Address             string                   `json:"address"`
	PublicKey           types.PortalAppPublicKey `json:"public_key"`
	ClientPublicKey     string                   `json:"client_public_key"`
	Signature           string                   `json:"signature"`
	PrivateKey          pgtype.Text              `json:"private_key"`
	Version             string                   `json:"version"`
}

type PortalApplicationNotification struct {
	ID            int32                  `json:"id"`
	ApplicationID types.PortalAppID      `json:"application_id"`
	Active        bool                   `json:"active"`
	Type          types.NotificationType `json:"type"`
	Destination   pgtype.Text            `json:"destination"`
	Trigger       pgtype.Text            `json:"trigger"`
	Events        []string               `json:"events"`
	UpdatedAt     pgtype.Timestamptz     `json:"updated_at"`
}

type PortalApplicationSetting struct {
	ID                int32              `json:"id"`
	ApplicationID     types.PortalAppID  `json:"application_id"`
	MonthlyRelayLimit int32              `json:"monthly_relay_limit"`
	Environment       types.Environment  `json:"environment"`
	FavoritedChainIDs []string           `json:"favorited_chain_ids"`
	SecretKey         pgtype.Text        `json:"secret_key"`
	SecretKeyRequired pgtype.Bool        `json:"secret_key_required"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PortalApplicationWhitelist struct {
	ID            int32               `json:"id"`
	ApplicationID types.PortalAppID   `json:"application_id"`
	Type          types.WhitelistType `json:"type"`
	Value         string              `json:"value"`
	ChainID       pgtype.Text         `json:"chain_id"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
}

type User struct {
	ID               types.UserID       `json:"id"`
	Email            types.Email        `json:"email"`
	SignedUp         bool               `json:"signed_up"`
	IconURL          pgtype.Text        `json:"icon_url"`
	UpdatesProduct   pgtype.Bool        `json:"updates_product"`
	UpdatesMarketing pgtype.Bool        `json:"updates_marketing"`
	BetaTester       pgtype.Bool        `json:"beta_tester"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserAuthProvider struct {
	ID             int32                `json:"id"`
	UserID         types.UserID         `json:"user_id"`
	Type           types.AuthType       `json:"type"`
	Provider       types.AuthProvider   `json:"provider"`
	ProviderUserID types.ProviderUserID `json:"provider_user_id"`
	Federated      bool                 `json:"federated"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
}

type UserRole struct {
	RoleName    string              `json:"role_name"`
	Permissions []types.Permissions `json:"permissions"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
}
