// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package postgresdriver

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/pokt-foundation/portal-db/types"
)

type AuthProvider string

const (
	AuthProviderAuth0 AuthProvider = "auth0"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type AuthType string

const (
	AuthTypeAuth0Github   AuthType = "auth0_github"
	AuthTypeAuth0Username AuthType = "auth0_username"
)

func (e *AuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthType(s)
	case string:
		*e = AuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthType: %T", src)
	}
	return nil
}

type NullAuthType struct {
	AuthType AuthType
	Valid    bool // Valid is true if AuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthType), nil
}

type ChainAuthType string

const (
	ChainAuthTypeBasicAuth   ChainAuthType = "basic_auth"
	ChainAuthTypeBearerToken ChainAuthType = "bearer_token"
	ChainAuthTypeNone        ChainAuthType = "none"
)

func (e *ChainAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainAuthType(s)
	case string:
		*e = ChainAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainAuthType: %T", src)
	}
	return nil
}

type NullChainAuthType struct {
	ChainAuthType ChainAuthType
	Valid         bool // Valid is true if ChainAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.ChainAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainAuthType), nil
}

type ChainCheckType string

const (
	ChainCheckTypeArchival ChainCheckType = "archival"
	ChainCheckTypeChain    ChainCheckType = "chain"
	ChainCheckTypeMerge    ChainCheckType = "merge"
	ChainCheckTypeSync     ChainCheckType = "sync"
)

func (e *ChainCheckType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainCheckType(s)
	case string:
		*e = ChainCheckType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainCheckType: %T", src)
	}
	return nil
}

type NullChainCheckType struct {
	ChainCheckType ChainCheckType
	Valid          bool // Valid is true if ChainCheckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainCheckType) Scan(value interface{}) error {
	if value == nil {
		ns.ChainCheckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainCheckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainCheckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainCheckType), nil
}

type Environment string

const (
	EnvironmentProduction Environment = "production"
	EnvironmentTest       Environment = "test"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type NotificationEvent string

const (
	NotificationEventFull          NotificationEvent = "full"
	NotificationEventHalf          NotificationEvent = "half"
	NotificationEventQuarter       NotificationEvent = "quarter"
	NotificationEventSignedUp      NotificationEvent = "signedUp"
	NotificationEventThreeQuarters NotificationEvent = "threeQuarters"
)

func (e *NotificationEvent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationEvent(s)
	case string:
		*e = NotificationEvent(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationEvent: %T", src)
	}
	return nil
}

type NullNotificationEvent struct {
	NotificationEvent NotificationEvent
	Valid             bool // Valid is true if NotificationEvent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationEvent) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationEvent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationEvent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationEvent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationEvent), nil
}

type NotificationType string

const (
	NotificationTypeEmail   NotificationType = "email"
	NotificationTypePortal  NotificationType = "portal"
	NotificationTypeWebhook NotificationType = "webhook"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Permissions string

const (
	PermissionsReadEndpoint     Permissions = "read:endpoint"
	PermissionsWriteEndpoint    Permissions = "write:endpoint"
	PermissionsDeleteEndpoint   Permissions = "delete:endpoint"
	PermissionsTransferEndpoint Permissions = "transfer:endpoint"
)

func (e *Permissions) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Permissions(s)
	case string:
		*e = Permissions(s)
	default:
		return fmt.Errorf("unsupported scan type for Permissions: %T", src)
	}
	return nil
}

type NullPermissions struct {
	Permissions Permissions
	Valid       bool // Valid is true if Permissions is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissions) Scan(value interface{}) error {
	if value == nil {
		ns.Permissions, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Permissions.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissions) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Permissions), nil
}

type WhitelistType string

const (
	WhitelistTypeBlockchains WhitelistType = "blockchains"
	WhitelistTypeContracts   WhitelistType = "contracts"
	WhitelistTypeMethods     WhitelistType = "methods"
	WhitelistTypeOrigins     WhitelistType = "origins"
	WhitelistTypeUserAgents  WhitelistType = "userAgents"
)

func (e *WhitelistType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhitelistType(s)
	case string:
		*e = WhitelistType(s)
	default:
		return fmt.Errorf("unsupported scan type for WhitelistType: %T", src)
	}
	return nil
}

type NullWhitelistType struct {
	WhitelistType WhitelistType
	Valid         bool // Valid is true if WhitelistType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhitelistType) Scan(value interface{}) error {
	if value == nil {
		ns.WhitelistType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhitelistType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhitelistType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhitelistType), nil
}

type Account struct {
	ID                      types.AccountID   `json:"id"`
	Name                    string            `json:"name"`
	PlanType                types.PayPlanType `json:"planType"`
	PartnerChainIDs         []string          `json:"partnerChainIds"`
	PartnerThroughputLimit  sql.NullInt32     `json:"partnerThroughputLimit"`
	PartnerApplicationLimit sql.NullInt32     `json:"partnerApplicationLimit"`
	CreatedAt               time.Time         `json:"createdAt"`
	UpdatedAt               time.Time         `json:"updatedAt"`
	Deleted                 bool              `json:"deleted"`
	DeletedAt               sql.NullTime      `json:"deletedAt"`
	LbID                    string            `json:"lbID"`
}

type AccountUserAccess struct {
	ID        int32           `json:"id"`
	AccountID types.AccountID `json:"accountID"`
	UserID    types.UserID    `json:"userID"`
	RoleName  types.RoleName  `json:"roleName"`
	Accepted  bool            `json:"accepted"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Chain struct {
	ID             types.ChainID  `json:"id"`
	Blockchain     string         `json:"blockchain"`
	Description    string         `json:"description"`
	EnforceResult  string         `json:"enforceResult"`
	Ticker         string         `json:"ticker"`
	Path           sql.NullString `json:"path"`
	BlockchainID   sql.NullInt32  `json:"blockchainID"`
	RequestTimeout sql.NullInt32  `json:"requestTimeout"`
	LogLimitBlocks sql.NullInt32  `json:"logLimitBlocks"`
	ChainAliases   []string       `json:"chainAliases"`
	AllowedMethods []string       `json:"allowedMethods"`
	Active         bool           `json:"active"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	Deleted        sql.NullBool   `json:"deleted"`
	DeletedAt      sql.NullTime   `json:"deletedAt"`
}

type ChainAltruist struct {
	ID        int32               `json:"id"`
	ChainID   types.ChainID       `json:"chainID"`
	URL       types.AltruistURL   `json:"url"`
	Auth      sql.NullString      `json:"auth"`
	AuthType  types.ChainAuthType `json:"authType"`
	CreatedAt time.Time           `json:"createdAt"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

type ChainCheck struct {
	ID        int32                `json:"id"`
	ChainID   types.ChainID        `json:"chainID"`
	Type      types.ChainCheckType `json:"type"`
	Payload   sql.NullString       `json:"payload"`
	ResultKey sql.NullString       `json:"resultKey"`
	Allowance sql.NullInt32        `json:"allowance"`
	CreatedAt time.Time            `json:"createdAt"`
	UpdatedAt time.Time            `json:"updatedAt"`
}

type ChainGigastakeRedirect struct {
	ID        int32                `json:"id"`
	ChainID   types.ChainID        `json:"chainID"`
	AccountID types.AccountID      `json:"accountID"`
	Alias     string               `json:"alias"`
	Domain    types.RedirectDomain `json:"domain"`
	CreatedAt time.Time            `json:"createdAt"`
	UpdatedAt time.Time            `json:"updatedAt"`
	LbID      string               `json:"lbID"`
}

type GlobalBlockedContract struct {
	ID             int32                `json:"id"`
	BlockedAddress types.BlockedAddress `json:"blockedAddress"`
	Active         bool                 `json:"active"`
	CreatedAt      time.Time            `json:"createdAt"`
	UpdatedAt      time.Time            `json:"updatedAt"`
}

type PayPlan struct {
	PlanType          types.PayPlanType `json:"planType"`
	ChainIDs          []string          `json:"chainIds"`
	MonthlyRelayLimit int32             `json:"monthlyRelayLimit"`
	ThroughputLimit   int32             `json:"throughputLimit"`
	ApplicationLimit  int32             `json:"applicationLimit"`
	CreatedAt         time.Time         `json:"createdAt"`
	UpdatedAt         time.Time         `json:"updatedAt"`
	DailyLimit        sql.NullInt32     `json:"dailyLimit"`
}

type PortalApplication struct {
	ID                 types.PortalAppID `json:"id"`
	AccountID          int32             `json:"accountID"`
	Name               string            `json:"name"`
	Gigastake          bool              `json:"gigastake"`
	Staked             bool              `json:"staked"`
	CreatedAt          time.Time         `json:"createdAt"`
	UpdatedAt          time.Time         `json:"updatedAt"`
	Deleted            bool              `json:"deleted"`
	DeletedAt          sql.NullTime      `json:"deletedAt"`
	ApplicationIDs     []string          `json:"applicationIds"`
	RequestTimeout     sql.NullInt32     `json:"requestTimeout"`
	GigastakeRedirect  sql.NullBool      `json:"gigastakeRedirect"`
	FirstDateSurpassed sql.NullTime      `json:"firstDateSurpassed"`
	CustomLimit        sql.NullInt32     `json:"customLimit"`
}

type PortalApplicationAat struct {
	ID              int32             `json:"id"`
	ApplicationID   types.PortalAppID `json:"applicationID"`
	Address         string            `json:"address"`
	PublicKey       string            `json:"publicKey"`
	ClientPublicKey string            `json:"clientPublicKey"`
	PrivateKey      string            `json:"privateKey"`
	Signature       string            `json:"signature"`
	Version         string            `json:"version"`
}

type PortalApplicationNotification struct {
	ID            int32                     `json:"id"`
	ApplicationID types.PortalAppID         `json:"applicationID"`
	Active        bool                      `json:"active"`
	Type          types.NotificationType    `json:"type"`
	Destination   sql.NullString            `json:"destination"`
	Trigger       sql.NullString            `json:"trigger"`
	Events        []types.NotificationEvent `json:"events"`
	UpdatedAt     time.Time                 `json:"updatedAt"`
}

type PortalApplicationSetting struct {
	ID                int32             `json:"id"`
	ApplicationID     types.PortalAppID `json:"applicationID"`
	MonthlyRelayLimit int32             `json:"monthlyRelayLimit"`
	Environment       types.Environment `json:"environment"`
	FavoritedChainIDs []string          `json:"favoritedChainIds"`
	SecretKey         sql.NullString    `json:"secretKey"`
	SecretKeyRequired sql.NullBool      `json:"secretKeyRequired"`
	UpdatedAt         time.Time         `json:"updatedAt"`
}

type PortalApplicationWhitelist struct {
	ID            int32               `json:"id"`
	ApplicationID types.PortalAppID   `json:"applicationID"`
	Type          types.WhitelistType `json:"type"`
	Value         string              `json:"value"`
	ChainID       sql.NullString      `json:"chainID"`
	CreatedAt     time.Time           `json:"createdAt"`
}

type StickinessOption struct {
	ID         int32             `json:"id"`
	LbID       types.PortalAppID `json:"lbID"`
	Duration   sql.NullString    `json:"duration"`
	StickyMax  sql.NullInt32     `json:"stickyMax"`
	Stickiness sql.NullBool      `json:"stickiness"`
	Origins    []string          `json:"origins"`
}

type User struct {
	ID        types.UserID `json:"id"`
	Email     types.Email  `json:"email"`
	SignedUp  bool         `json:"signedUp"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type UserAuthProvider struct {
	ID             int32              `json:"id"`
	UserID         types.UserID       `json:"userID"`
	Type           types.AuthType     `json:"type"`
	Provider       types.AuthProvider `json:"provider"`
	ProviderUserID string             `json:"providerUserID"`
	Federated      bool               `json:"federated"`
	CreatedAt      time.Time          `json:"createdAt"`
}

type UserRole struct {
	RoleName    string              `json:"roleName"`
	Permissions []types.Permissions `json:"permissions"`
	CreatedAt   time.Time           `json:"createdAt"`
	UpdatedAt   time.Time           `json:"updatedAt"`
}
