// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package postgresdriver

import (
	"context"
)

const placeholder = `-- name: Placeholder :exec
SELECT id, blockchain, description, enforce_result, path, ticker, chain_id, request_timeout, log_limit_blocks, blockchain_aliases, allowed_methods, active, created_at, updated_at, deleted FROM blockchains
`

// only here to avoid SQLC erroring out when trying to gen types from schema
func (q *Queries) Placeholder(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, placeholder)
	return err
}
