// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package postgresdriver

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pokt-foundation/portal-db/v2/types"
)

const addGlobalBlockedContract = `-- name: AddGlobalBlockedContract :exec
INSERT INTO global_blocked_contracts (blocked_address, created_at, updated_at)
VALUES ($1, $2, $3)
`

type AddGlobalBlockedContractParams struct {
	BlockedAddress types.BlockedAddress `json:"blocked_address"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) AddGlobalBlockedContract(ctx context.Context, arg AddGlobalBlockedContractParams) error {
	_, err := q.db.Exec(ctx, addGlobalBlockedContract, arg.BlockedAddress, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS(
        SELECT 1
        FROM accounts
        WHERE id = $1
            AND deleted = false
    )
`

func (q *Queries) CheckAccountExists(ctx context.Context, id types.AccountID) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkAccountUserAccepted = `-- name: CheckAccountUserAccepted :one
SELECT accepted
FROM account_user_access
WHERE user_id = $1
    AND portal_application_id = $2
`

type CheckAccountUserAcceptedParams struct {
	UserID              types.UserID      `json:"user_id"`
	PortalApplicationID types.PortalAppID `json:"portal_application_id"`
}

func (q *Queries) CheckAccountUserAccepted(ctx context.Context, arg CheckAccountUserAcceptedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountUserAccepted, arg.UserID, arg.PortalApplicationID)
	var accepted bool
	err := row.Scan(&accepted)
	return accepted, err
}

const checkAccountUserExists = `-- name: CheckAccountUserExists :one
SELECT EXISTS (
        SELECT 1
        FROM account_user_access
        WHERE user_id = $1
            AND portal_application_id = $2
    )
`

type CheckAccountUserExistsParams struct {
	UserID              types.UserID      `json:"user_id"`
	PortalApplicationID types.PortalAppID `json:"portal_application_id"`
}

func (q *Queries) CheckAccountUserExists(ctx context.Context, arg CheckAccountUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountUserExists, arg.UserID, arg.PortalApplicationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkAccountUserRole = `-- name: CheckAccountUserRole :one
SELECT role_name
FROM account_user_access
WHERE user_id = $1
    AND account_id = $2
`

type CheckAccountUserRoleParams struct {
	UserID    types.UserID    `json:"user_id"`
	AccountID types.AccountID `json:"account_id"`
}

func (q *Queries) CheckAccountUserRole(ctx context.Context, arg CheckAccountUserRoleParams) (types.RoleName, error) {
	row := q.db.QueryRow(ctx, checkAccountUserRole, arg.UserID, arg.AccountID)
	var role_name types.RoleName
	err := row.Scan(&role_name)
	return role_name, err
}

const checkAliasExists = `-- name: CheckAliasExists :one
SELECT EXISTS(
        SELECT 1
        FROM chain_alias_domains
        WHERE chain_id = $1
            AND alias = $2
    )
`

type CheckAliasExistsParams struct {
	ChainID types.RelayChainID `json:"chain_id"`
	Alias   types.ChainAlias   `json:"alias"`
}

func (q *Queries) CheckAliasExists(ctx context.Context, arg CheckAliasExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAliasExists, arg.ChainID, arg.Alias)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkChainExists = `-- name: CheckChainExists :one
SELECT EXISTS(
        SELECT 1
        FROM chains
        WHERE id = $1
            AND deleted = false
    )
`

func (q *Queries) CheckChainExists(ctx context.Context, id types.RelayChainID) (bool, error) {
	row := q.db.QueryRow(ctx, checkChainExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIDExists = `-- name: CheckIDExists :one
SELECT EXISTS (
        SELECT 1
        FROM (
                SELECT id
                FROM portal_applications
                WHERE portal_applications.id = $1::VARCHAR
                UNION ALL
                SELECT id
                FROM portal_application_aats
                WHERE portal_application_aats.id = $1::VARCHAR
                UNION ALL
                SELECT id
                FROM gigastake_applications
                WHERE gigastake_applications.id = $1::VARCHAR
                UNION ALL
                SELECT id
                FROM accounts
                WHERE accounts.id = $1::VARCHAR
                UNION ALL
                SELECT id
                FROM users
                WHERE users.id = $1::VARCHAR
            ) AS id_table
    )
`

func (q *Queries) CheckIDExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIDExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIfAppWhitelistExists = `-- name: CheckIfAppWhitelistExists :one
SELECT EXISTS(
        SELECT 1
        FROM portal_application_whitelists
        WHERE application_id = $1
            AND type = $2
            AND value = $3
            AND chain_id IS NULL
    )
`

type CheckIfAppWhitelistExistsParams struct {
	ApplicationID types.PortalAppID   `json:"application_id"`
	Type          types.WhitelistType `json:"type"`
	Value         string              `json:"value"`
}

func (q *Queries) CheckIfAppWhitelistExists(ctx context.Context, arg CheckIfAppWhitelistExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfAppWhitelistExists, arg.ApplicationID, arg.Type, arg.Value)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPlanExists = `-- name: CheckPlanExists :one
SELECT EXISTS(
        SELECT 1
        FROM pay_plans
        WHERE plan_type = $1
    )
`

func (q *Queries) CheckPlanExists(ctx context.Context, planType types.PayPlanType) (bool, error) {
	row := q.db.QueryRow(ctx, checkPlanExists, planType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPlanTypeExists = `-- name: CheckPlanTypeExists :one
SELECT EXISTS(
        SELECT 1
        FROM pay_plans
        WHERE plan_type = $1
    )
`

func (q *Queries) CheckPlanTypeExists(ctx context.Context, planType types.PayPlanType) (bool, error) {
	row := q.db.QueryRow(ctx, checkPlanTypeExists, planType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPortalAppExists = `-- name: CheckPortalAppExists :one
SELECT EXISTS(
        SELECT 1
        FROM portal_applications
        WHERE id = $1
            AND deleted = false
    )
`

func (q *Queries) CheckPortalAppExists(ctx context.Context, id types.PortalAppID) (bool, error) {
	row := q.db.QueryRow(ctx, checkPortalAppExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserAccountExists = `-- name: CheckUserAccountExists :one
SELECT EXISTS (
        SELECT 1
        FROM account_user_access
        WHERE user_id = $1
    )
`

func (q *Queries) CheckUserAccountExists(ctx context.Context, userID types.UserID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserAccountExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserEmail = `-- name: CheckUserEmail :one
SELECT email
FROM users
WHERE id = $1
`

func (q *Queries) CheckUserEmail(ctx context.Context, id types.UserID) (types.Email, error) {
	row := q.db.QueryRow(ctx, checkUserEmail, id)
	var email types.Email
	err := row.Scan(&email)
	return email, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(
        SELECT 1
        FROM users
        WHERE id = $1
    )
`

func (q *Queries) CheckUserExists(ctx context.Context, id types.UserID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserIDFromEmail = `-- name: CheckUserIDFromEmail :one
SELECT id
FROM users
WHERE email = $1
`

func (q *Queries) CheckUserIDFromEmail(ctx context.Context, email types.Email) (types.UserID, error) {
	row := q.db.QueryRow(ctx, checkUserIDFromEmail, email)
	var id types.UserID
	err := row.Scan(&id)
	return id, err
}

const checkUserProviderExists = `-- name: CheckUserProviderExists :one
SELECT EXISTS (
        SELECT 1
        FROM users
            JOIN user_auth_providers ON users.id = user_auth_providers.user_id
        WHERE users.email = $1
            AND user_auth_providers.type = $2
    )
`

type CheckUserProviderExistsParams struct {
	Email types.Email    `json:"email"`
	Type  types.AuthType `json:"type"`
}

func (q *Queries) CheckUserProviderExists(ctx context.Context, arg CheckUserProviderExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserProviderExists, arg.Email, arg.Type)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserNewSignUp = `-- name: CreateUserNewSignUp :one
WITH inserted_user AS (
    INSERT INTO users (id, email, signed_up, created_at, updated_at)
    VALUES ($1, $2, true, $3, $4) ON CONFLICT (email) DO NOTHING
    RETURNING id
)
INSERT INTO user_auth_providers (
        user_id,
        type,
        provider,
        provider_user_id,
        federated
    )
VALUES (
        (
            SELECT COALESCE(
                    (
                        SELECT id
                        FROM inserted_user
                    ),
                    (
                        SELECT id
                        FROM users
                        WHERE users.email = $2
                    )
                )
        ),
        $5,
        $6,
        $7,
        $8
    )
RETURNING user_id
`

type CreateUserNewSignUpParams struct {
	ID             types.UserID         `json:"id"`
	Email          types.Email          `json:"email"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `json:"updated_at"`
	Type           types.AuthType       `json:"type"`
	Provider       types.AuthProvider   `json:"provider"`
	ProviderUserID types.ProviderUserID `json:"provider_user_id"`
	Federated      bool                 `json:"federated"`
}

func (q *Queries) CreateUserNewSignUp(ctx context.Context, arg CreateUserNewSignUpParams) (types.UserID, error) {
	row := q.db.QueryRow(ctx, createUserNewSignUp,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
		arg.Provider,
		arg.ProviderUserID,
		arg.Federated,
	)
	var user_id types.UserID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET deleted = true,
    deleted_at = $2
WHERE id = $1
`

type DeleteAccountParams struct {
	ID        types.AccountID    `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.DeletedAt)
	return err
}

const deleteAccountUser = `-- name: DeleteAccountUser :exec
DELETE FROM account_user_access
WHERE portal_application_id = $1
    AND user_id = $2
`

type DeleteAccountUserParams struct {
	PortalApplicationID types.PortalAppID `json:"portal_application_id"`
	UserID              types.UserID      `json:"user_id"`
}

func (q *Queries) DeleteAccountUser(ctx context.Context, arg DeleteAccountUserParams) error {
	_, err := q.db.Exec(ctx, deleteAccountUser, arg.PortalApplicationID, arg.UserID)
	return err
}

const deleteChainAliasDomain = `-- name: DeleteChainAliasDomain :exec
DELETE FROM chain_alias_domains
WHERE chain_id = $1
    AND alias = $2
`

type DeleteChainAliasDomainParams struct {
	ChainID types.RelayChainID `json:"chain_id"`
	Alias   types.ChainAlias   `json:"alias"`
}

func (q *Queries) DeleteChainAliasDomain(ctx context.Context, arg DeleteChainAliasDomainParams) error {
	_, err := q.db.Exec(ctx, deleteChainAliasDomain, arg.ChainID, arg.Alias)
	return err
}

const deletePortalApp = `-- name: DeletePortalApp :exec
UPDATE portal_applications
SET deleted = true,
    deleted_at = $2
WHERE id = $1
`

type DeletePortalAppParams struct {
	ID        types.PortalAppID  `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeletePortalApp(ctx context.Context, arg DeletePortalAppParams) error {
	_, err := q.db.Exec(ctx, deletePortalApp, arg.ID, arg.DeletedAt)
	return err
}

const deleteUnusedChainAliasDomains = `-- name: DeleteUnusedChainAliasDomains :exec
DELETE FROM chain_alias_domains
WHERE chain_id = $1
    AND alias NOT IN (
        SELECT unnest($2::VARCHAR [])
    )
`

type DeleteUnusedChainAliasDomainsParams struct {
	ChainID types.RelayChainID `json:"chain_id"`
	Aliases []string           `json:"aliases"`
}

func (q *Queries) DeleteUnusedChainAliasDomains(ctx context.Context, arg DeleteUnusedChainAliasDomainsParams) error {
	_, err := q.db.Exec(ctx, deleteUnusedChainAliasDomains, arg.ChainID, arg.Aliases)
	return err
}

const deleteUnusedChainAltruists = `-- name: DeleteUnusedChainAltruists :exec
DELETE FROM chain_altruists
WHERE chain_id = $1
    AND url NOT IN (
        SELECT unnest($2::VARCHAR [])
    )
`

type DeleteUnusedChainAltruistsParams struct {
	ChainID types.RelayChainID `json:"chain_id"`
	URLs    []string           `json:"urls"`
}

func (q *Queries) DeleteUnusedChainAltruists(ctx context.Context, arg DeleteUnusedChainAltruistsParams) error {
	_, err := q.db.Exec(ctx, deleteUnusedChainAltruists, arg.ChainID, arg.URLs)
	return err
}

const deleteUnusedChainChecks = `-- name: DeleteUnusedChainChecks :exec
DELETE FROM chain_checks
WHERE chain_id = $1
    AND type NOT IN (
        SELECT unnest($2::chain_check_type [])
    )
`

type DeleteUnusedChainChecksParams struct {
	ChainID types.RelayChainID     `json:"chain_id"`
	Types   []types.ChainCheckType `json:"types"`
}

func (q *Queries) DeleteUnusedChainChecks(ctx context.Context, arg DeleteUnusedChainChecksParams) error {
	_, err := q.db.Exec(ctx, deleteUnusedChainChecks, arg.ChainID, arg.Types)
	return err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id types.UserID) (types.UserID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getAccountOwnerEmail = `-- name: GetAccountOwnerEmail :one
SELECT users.email
FROM users
    JOIN account_user_access AS aua ON users.id = aua.user_id
WHERE aua.account_id = $1
    AND aua.owner = true
`

func (q *Queries) GetAccountOwnerEmail(ctx context.Context, accountID types.AccountID) (types.Email, error) {
	row := q.db.QueryRow(ctx, getAccountOwnerEmail, accountID)
	var email types.Email
	err := row.Scan(&email)
	return email, err
}

const getLastCreatedUserID = `-- name: GetLastCreatedUserID :one
SELECT id
FROM users
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastCreatedUserID(ctx context.Context) (types.UserID, error) {
	row := q.db.QueryRow(ctx, getLastCreatedUserID)
	var id types.UserID
	err := row.Scan(&id)
	return id, err
}

const getPortalUserID = `-- name: GetPortalUserID :one
SELECT user_id
FROM user_auth_providers
WHERE provider_user_id = $1
`

func (q *Queries) GetPortalUserID(ctx context.Context, providerUserID types.ProviderUserID) (types.UserID, error) {
	row := q.db.QueryRow(ctx, getPortalUserID, providerUserID)
	var user_id types.UserID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserDataFromAuthProviderUserID = `-- name: GetUserDataFromAuthProviderUserID :one
SELECT users.id, users.email, users.signed_up, users.created_at, users.updated_at,
    json_agg(user_auth_providers.*) AS auth_providers
FROM users
    LEFT JOIN user_auth_providers ON users.id = user_auth_providers.user_id
WHERE user_auth_providers.provider_user_id = $1
GROUP BY users.id
`

type GetUserDataFromAuthProviderUserIDRow struct {
	ID            types.UserID       `json:"id"`
	Email         types.Email        `json:"email"`
	SignedUp      bool               `json:"signed_up"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AuthProviders []byte             `json:"auth_providers"`
}

func (q *Queries) GetUserDataFromAuthProviderUserID(ctx context.Context, providerUserID types.ProviderUserID) (GetUserDataFromAuthProviderUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserDataFromAuthProviderUserID, providerUserID)
	var i GetUserDataFromAuthProviderUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SignedUp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthProviders,
	)
	return i, err
}

const getUserDataFromPortalUserID = `-- name: GetUserDataFromPortalUserID :one
SELECT users.id, users.email, users.signed_up, users.created_at, users.updated_at,
    json_agg(user_auth_providers.*) AS auth_providers
FROM users
    LEFT JOIN user_auth_providers ON users.id = user_auth_providers.user_id
WHERE users.id = $1
GROUP BY users.id
`

type GetUserDataFromPortalUserIDRow struct {
	ID            types.UserID       `json:"id"`
	Email         types.Email        `json:"email"`
	SignedUp      bool               `json:"signed_up"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AuthProviders []byte             `json:"auth_providers"`
}

func (q *Queries) GetUserDataFromPortalUserID(ctx context.Context, id types.UserID) (GetUserDataFromPortalUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserDataFromPortalUserID, id)
	var i GetUserDataFromPortalUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SignedUp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthProviders,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email
FROM users
WHERE users.id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id types.UserID) (types.Email, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email types.Email
	err := row.Scan(&email)
	return email, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (
        id,
        plan_type,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4)
RETURNING id, plan_type, partner_chain_ids, partner_throughput_limit, partner_application_limit, created_at, updated_at, deleted, deleted_at
`

type InsertAccountParams struct {
	ID        types.AccountID    `json:"id"`
	PlanType  types.PayPlanType  `json:"plan_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.PlanType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlanType,
		&i.PartnerChainIDs,
		&i.PartnerThroughputLimit,
		&i.PartnerApplicationLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
	)
	return i, err
}

const insertAccountUserAccess = `-- name: InsertAccountUserAccess :one
WITH updated_user AS (
    UPDATE users
    SET email = $7
    WHERE id = $1
    RETURNING id,
        email
) -- Must update email to trigger listener notification for users table
INSERT INTO account_user_access (
        user_id,
        account_id,
        portal_application_id,
        role_name,
        owner,
        accepted,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        NULLIF($9::VARCHAR, ''),
        $3,
        $4,
        $5,
        $6,
        $8
    )
RETURNING user_id
`

type InsertAccountUserAccessParams struct {
	UserID              types.UserID       `json:"user_id"`
	AccountID           types.AccountID    `json:"account_id"`
	RoleName            types.RoleName     `json:"role_name"`
	Owner               bool               `json:"owner"`
	Accepted            bool               `json:"accepted"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Email               types.Email        `json:"email"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PortalApplicationID string             `json:"portal_application_id"`
}

func (q *Queries) InsertAccountUserAccess(ctx context.Context, arg InsertAccountUserAccessParams) (types.UserID, error) {
	row := q.db.QueryRow(ctx, insertAccountUserAccess,
		arg.UserID,
		arg.AccountID,
		arg.RoleName,
		arg.Owner,
		arg.Accepted,
		arg.CreatedAt,
		arg.Email,
		arg.UpdatedAt,
		arg.PortalApplicationID,
	)
	var user_id types.UserID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertAccountUserAccessNoUser = `-- name: InsertAccountUserAccessNoUser :one
WITH inserted_user AS (
    INSERT INTO users (
            id,
            email,
            signed_up,
            created_at,
            updated_at
        )
    VALUES ($1, $2, false, $3, $4)
    RETURNING id,
        email
)
INSERT INTO account_user_access (
        user_id,
        account_id,
        portal_application_id,
        role_name,
        owner,
        accepted,
        created_at,
        updated_at
    )
VALUES (
        (
            SELECT id
            FROM inserted_user
        ),
        $6,
        $7,
        $5,
        false,
        false,
        $3,
        $4
    )
RETURNING user_id
`

type InsertAccountUserAccessNoUserParams struct {
	ID                  types.UserID       `json:"id"`
	Email               types.Email        `json:"email"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RoleName            types.RoleName     `json:"role_name"`
	AccountID           types.AccountID    `json:"account_id"`
	PortalApplicationID types.PortalAppID  `json:"portal_application_id"`
}

func (q *Queries) InsertAccountUserAccessNoUser(ctx context.Context, arg InsertAccountUserAccessNoUserParams) (types.UserID, error) {
	row := q.db.QueryRow(ctx, insertAccountUserAccessNoUser,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RoleName,
		arg.AccountID,
		arg.PortalApplicationID,
	)
	var user_id types.UserID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertChain = `-- name: InsertChain :one
INSERT INTO chains (
        id,
        blockchain,
        description,
        enforce_result,
        path,
        ticker,
        request_timeout,
        log_limit_blocks,
        allowed_methods,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    )
RETURNING id
`

type InsertChainParams struct {
	ID             types.RelayChainID `json:"id"`
	Blockchain     pgtype.Text        `json:"blockchain"`
	Description    pgtype.Text        `json:"description"`
	EnforceResult  pgtype.Text        `json:"enforce_result"`
	Path           pgtype.Text        `json:"path"`
	Ticker         pgtype.Text        `json:"ticker"`
	RequestTimeout pgtype.Int4        `json:"request_timeout"`
	LogLimitBlocks pgtype.Int4        `json:"log_limit_blocks"`
	AllowedMethods []string           `json:"allowed_methods"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertChain(ctx context.Context, arg InsertChainParams) (types.RelayChainID, error) {
	row := q.db.QueryRow(ctx, insertChain,
		arg.ID,
		arg.Blockchain,
		arg.Description,
		arg.EnforceResult,
		arg.Path,
		arg.Ticker,
		arg.RequestTimeout,
		arg.LogLimitBlocks,
		arg.AllowedMethods,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id types.RelayChainID
	err := row.Scan(&id)
	return id, err
}

const insertGigastakeApp = `-- name: InsertGigastakeApp :exec
WITH new_gigastake_application AS (
    INSERT INTO gigastake_applications (
            id,
            name,
            address,
            public_key,
            client_public_key,
            signature,
            version,
            created_at,
            updated_at
        )
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id
)
INSERT INTO chains_gigastake_applications (chain_id, gigastake_application_id)
SELECT unnest($10::VARCHAR []),
    (
        SELECT id
        FROM new_gigastake_application
    ) ON CONFLICT (chain_id, gigastake_application_id) DO NOTHING
`

type InsertGigastakeAppParams struct {
	ID              types.GigastakeAppID `json:"id"`
	Name            string               `json:"name"`
	Address         string               `json:"address"`
	PublicKey       string               `json:"public_key"`
	ClientPublicKey string               `json:"client_public_key"`
	Signature       string               `json:"signature"`
	Version         string               `json:"version"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
	ChainIDs        []string             `json:"chain_ids"`
}

func (q *Queries) InsertGigastakeApp(ctx context.Context, arg InsertGigastakeAppParams) error {
	_, err := q.db.Exec(ctx, insertGigastakeApp,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.PublicKey,
		arg.ClientPublicKey,
		arg.Signature,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ChainIDs,
	)
	return err
}

const insertPortalApplication = `-- name: InsertPortalApplication :one
INSERT INTO portal_applications (
        id,
        account_id,
        name,
        created_at,
        updated_at,
        request_timeout,
        first_date_surpassed,
        -- legacy field
        plan_type,
        -- legacy field
        daily_limit,
        -- legacy field
        custom_limit
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
RETURNING id, account_id, name, created_at, updated_at, deleted, deleted_at, request_timeout, first_date_surpassed, plan_type, daily_limit, custom_limit
`

type InsertPortalApplicationParams struct {
	ID                 types.PortalAppID  `json:"id"`
	AccountID          pgtype.Text        `json:"account_id"`
	Name               string             `json:"name"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RequestTimeout     pgtype.Int4        `json:"request_timeout"`
	FirstDateSurpassed pgtype.Timestamptz `json:"first_date_surpassed"`
	PlanType           types.PayPlanType  `json:"plan_type"`
	DailyLimit         pgtype.Int4        `json:"daily_limit"`
	CustomLimit        pgtype.Int4        `json:"custom_limit"`
}

func (q *Queries) InsertPortalApplication(ctx context.Context, arg InsertPortalApplicationParams) (PortalApplication, error) {
	row := q.db.QueryRow(ctx, insertPortalApplication,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RequestTimeout,
		arg.FirstDateSurpassed,
		arg.PlanType,
		arg.DailyLimit,
		arg.CustomLimit,
	)
	var i PortalApplication
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.RequestTimeout,
		&i.FirstDateSurpassed,
		&i.PlanType,
		&i.DailyLimit,
		&i.CustomLimit,
	)
	return i, err
}

const insertPortalApplicationAAT = `-- name: InsertPortalApplicationAAT :one
INSERT INTO portal_application_aats (
        id,
        portal_application_id,
        address,
        public_key,
        private_key,
        client_public_key,
        signature,
        version
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, portal_application_id, address, public_key, client_public_key, signature, private_key, version
`

type InsertPortalApplicationAATParams struct {
	ID                  types.ProtocolAppID      `json:"id"`
	PortalApplicationID types.PortalAppID        `json:"portal_application_id"`
	Address             string                   `json:"address"`
	PublicKey           types.PortalAppPublicKey `json:"public_key"`
	PrivateKey          pgtype.Text              `json:"private_key"`
	ClientPublicKey     string                   `json:"client_public_key"`
	Signature           string                   `json:"signature"`
	Version             string                   `json:"version"`
}

func (q *Queries) InsertPortalApplicationAAT(ctx context.Context, arg InsertPortalApplicationAATParams) (PortalApplicationAat, error) {
	row := q.db.QueryRow(ctx, insertPortalApplicationAAT,
		arg.ID,
		arg.PortalApplicationID,
		arg.Address,
		arg.PublicKey,
		arg.PrivateKey,
		arg.ClientPublicKey,
		arg.Signature,
		arg.Version,
	)
	var i PortalApplicationAat
	err := row.Scan(
		&i.ID,
		&i.PortalApplicationID,
		&i.Address,
		&i.PublicKey,
		&i.ClientPublicKey,
		&i.Signature,
		&i.PrivateKey,
		&i.Version,
	)
	return i, err
}

const insertPortalApplicationSetting = `-- name: InsertPortalApplicationSetting :one
INSERT INTO portal_application_settings (
        application_id,
        secret_key,
        secret_key_required,
        monthly_relay_limit,
        environment
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, application_id, monthly_relay_limit, environment, favorited_chain_ids, secret_key, secret_key_required, updated_at
`

type InsertPortalApplicationSettingParams struct {
	ApplicationID     types.PortalAppID `json:"application_id"`
	SecretKey         pgtype.Text       `json:"secret_key"`
	SecretKeyRequired pgtype.Bool       `json:"secret_key_required"`
	MonthlyRelayLimit int32             `json:"monthly_relay_limit"`
	Environment       types.Environment `json:"environment"`
}

func (q *Queries) InsertPortalApplicationSetting(ctx context.Context, arg InsertPortalApplicationSettingParams) (PortalApplicationSetting, error) {
	row := q.db.QueryRow(ctx, insertPortalApplicationSetting,
		arg.ApplicationID,
		arg.SecretKey,
		arg.SecretKeyRequired,
		arg.MonthlyRelayLimit,
		arg.Environment,
	)
	var i PortalApplicationSetting
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.MonthlyRelayLimit,
		&i.Environment,
		&i.FavoritedChainIDs,
		&i.SecretKey,
		&i.SecretKeyRequired,
		&i.UpdatedAt,
	)
	return i, err
}

const removeGlobalBlockedContract = `-- name: RemoveGlobalBlockedContract :one
DELETE FROM global_blocked_contracts
WHERE blocked_address = $1
RETURNING id
`

func (q *Queries) RemoveGlobalBlockedContract(ctx context.Context, blockedAddress types.BlockedAddress) (int32, error) {
	row := q.db.QueryRow(ctx, removeGlobalBlockedContract, blockedAddress)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const selectAccount = `-- name: SelectAccount :one
WITH app_role_agg_owner AS (
    SELECT aua.user_id,
        aua.account_id,
        jsonb_object_agg(pa.id, 'OWNER') AS portal_application_roles
    FROM account_user_access AS aua
        JOIN portal_applications AS pa ON aua.account_id = pa.account_id
    WHERE aua.owner = true
    GROUP BY aua.user_id,
        aua.account_id
),
app_role_agg_non_owner AS (
    SELECT aua.user_id,
        aua.account_id,
        jsonb_object_agg(aua.portal_application_id, aua.role_name) AS portal_application_roles
    FROM account_user_access AS aua
        JOIN portal_applications AS pa ON aua.portal_application_id = pa.id
    WHERE aua.owner = false
    GROUP BY aua.user_id,
        aua.account_id
),
app_role_agg AS (
    SELECT COALESCE(aro.user_id, aroo.user_id) as user_id,
        COALESCE(aro.account_id, aroo.account_id) as account_id,
        COALESCE(aro.portal_application_roles, '{}'::jsonb) || COALESCE(aroo.portal_application_roles, '{}'::jsonb) as portal_application_roles
    FROM app_role_agg_owner aro
        FULL JOIN app_role_agg_non_owner aroo ON aro.user_id = aroo.user_id
        AND aro.account_id = aroo.account_id
)
SELECT a.id, a.plan_type, a.partner_chain_ids, a.partner_throughput_limit, a.partner_application_limit, a.created_at, a.updated_at, a.deleted, a.deleted_at,
    ai.covalent_api_key_free,
    ai.covalent_api_key_paid,
    json_agg(
        json_build_object(
            'user_id',
            u.id,
            'email',
            u.email,
            'accepted',
            aua.accepted,
            'owner',
            aua.owner,
            'portal_application_roles',
            ara.portal_application_roles
        )
    ) AS users
FROM accounts AS a
    LEFT JOIN account_user_access AS aua ON a.id = aua.account_id
    LEFT JOIN portal_applications AS pa ON aua.portal_application_id = pa.id
    LEFT JOIN account_integrations AS ai ON a.id = ai.account_id
    LEFT JOIN users AS u ON aua.user_id = u.id
    LEFT JOIN user_roles AS ur ON aua.role_name = ur.role_name
    LEFT JOIN app_role_agg AS ara ON u.id = ara.user_id
    AND a.id = ara.account_id
WHERE a.id = $1
GROUP BY a.id,
    ai.covalent_api_key_free,
    ai.covalent_api_key_paid
`

type SelectAccountRow struct {
	ID                      types.AccountID    `json:"id"`
	PlanType                types.PayPlanType  `json:"plan_type"`
	PartnerChainIDs         []string           `json:"partner_chain_ids"`
	PartnerThroughputLimit  pgtype.Int4        `json:"partner_throughput_limit"`
	PartnerApplicationLimit pgtype.Int4        `json:"partner_application_limit"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Deleted                 bool               `json:"deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	CovalentAPIKeyFree      pgtype.Text        `json:"covalent_api_key_free"`
	CovalentAPIKeyPaid      pgtype.Text        `json:"covalent_api_key_paid"`
	Users                   []byte             `json:"users"`
}

func (q *Queries) SelectAccount(ctx context.Context, id types.AccountID) (SelectAccountRow, error) {
	row := q.db.QueryRow(ctx, selectAccount, id)
	var i SelectAccountRow
	err := row.Scan(
		&i.ID,
		&i.PlanType,
		&i.PartnerChainIDs,
		&i.PartnerThroughputLimit,
		&i.PartnerApplicationLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.CovalentAPIKeyFree,
		&i.CovalentAPIKeyPaid,
		&i.Users,
	)
	return i, err
}

const selectAccounts = `-- name: SelectAccounts :many
WITH app_role_agg_owner AS (
    SELECT aua.user_id,
        aua.account_id,
        jsonb_object_agg(pa.id, 'OWNER') AS portal_application_roles
    FROM account_user_access AS aua
        JOIN portal_applications AS pa ON aua.account_id = pa.account_id
    WHERE aua.owner = true
    GROUP BY aua.user_id,
        aua.account_id
),
app_role_agg_non_owner AS (
    SELECT aua.user_id,
        aua.account_id,
        jsonb_object_agg(aua.portal_application_id, aua.role_name) AS portal_application_roles
    FROM account_user_access AS aua
        JOIN portal_applications AS pa ON aua.portal_application_id = pa.id
    WHERE aua.owner = false
    GROUP BY aua.user_id,
        aua.account_id
),
app_role_agg AS (
    SELECT COALESCE(aro.user_id, aroo.user_id) as user_id,
        COALESCE(aro.account_id, aroo.account_id) as account_id,
        COALESCE(aro.portal_application_roles, '{}'::jsonb) || COALESCE(aroo.portal_application_roles, '{}'::jsonb) as portal_application_roles
    FROM app_role_agg_owner aro
        FULL JOIN app_role_agg_non_owner aroo ON aro.user_id = aroo.user_id
        AND aro.account_id = aroo.account_id
)
SELECT a.id, a.plan_type, a.partner_chain_ids, a.partner_throughput_limit, a.partner_application_limit, a.created_at, a.updated_at, a.deleted, a.deleted_at,
    ai.covalent_api_key_free,
    ai.covalent_api_key_paid,
    json_agg(
        json_build_object(
            'user_id',
            u.id,
            'email',
            u.email,
            'accepted',
            aua.accepted,
            'owner',
            aua.owner,
            'portal_application_roles',
            ara.portal_application_roles
        )
    ) AS users
FROM accounts AS a
    LEFT JOIN account_user_access AS aua ON a.id = aua.account_id
    LEFT JOIN portal_applications AS pa ON aua.portal_application_id = pa.id
    LEFT JOIN account_integrations AS ai ON a.id = ai.account_id
    LEFT JOIN users AS u ON aua.user_id = u.id
    LEFT JOIN user_roles AS ur ON aua.role_name = ur.role_name
    LEFT JOIN app_role_agg AS ara ON u.id = ara.user_id
    AND a.id = ara.account_id
WHERE (
        $1::BOOLEAN
        OR a.deleted = false
    )
GROUP BY a.id,
    ai.covalent_api_key_free,
    ai.covalent_api_key_paid
`

type SelectAccountsRow struct {
	ID                      types.AccountID    `json:"id"`
	PlanType                types.PayPlanType  `json:"plan_type"`
	PartnerChainIDs         []string           `json:"partner_chain_ids"`
	PartnerThroughputLimit  pgtype.Int4        `json:"partner_throughput_limit"`
	PartnerApplicationLimit pgtype.Int4        `json:"partner_application_limit"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Deleted                 bool               `json:"deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	CovalentAPIKeyFree      pgtype.Text        `json:"covalent_api_key_free"`
	CovalentAPIKeyPaid      pgtype.Text        `json:"covalent_api_key_paid"`
	Users                   []byte             `json:"users"`
}

func (q *Queries) SelectAccounts(ctx context.Context, dollar_1 bool) ([]SelectAccountsRow, error) {
	rows, err := q.db.Query(ctx, selectAccounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAccountsRow
	for rows.Next() {
		var i SelectAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanType,
			&i.PartnerChainIDs,
			&i.PartnerThroughputLimit,
			&i.PartnerApplicationLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
			&i.CovalentAPIKeyFree,
			&i.CovalentAPIKeyPaid,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChain = `-- name: SelectChain :one
SELECT c.id, c.blockchain, c.description, c.enforce_result, c.ticker, c.path, c.request_timeout, c.log_limit_blocks, c.allowed_methods, c.active, c.created_at, c.updated_at, c.deleted, c.deleted_at,
    COALESCE(
        json_agg(DISTINCT ca) FILTER (
            WHERE ca.id IS NOT NULL
        ),
        '[]'
    )::json AS chain_altruists,
    COALESCE(
        json_agg(DISTINCT cc) FILTER (
            WHERE cc.id IS NOT NULL
        ),
        '[]'
    )::json AS chain_checks,
    COALESCE(
        json_object_agg(COALESCE(cga.alias, 'null'), cga.domains) FILTER (
            WHERE cga.alias IS NOT NULL
        ),
        '{}'
    )::json AS alias_domains_map
FROM chains c
    LEFT JOIN chain_altruists ca ON c.id = ca.chain_id
    LEFT JOIN chain_checks cc ON c.id = cc.chain_id
    LEFT JOIN chain_alias_domains cga ON c.id = cga.chain_id
WHERE c.id = $1
GROUP BY c.id
`

type SelectChainRow struct {
	ID              types.RelayChainID `json:"id"`
	Blockchain      pgtype.Text        `json:"blockchain"`
	Description     pgtype.Text        `json:"description"`
	EnforceResult   pgtype.Text        `json:"enforce_result"`
	Ticker          pgtype.Text        `json:"ticker"`
	Path            pgtype.Text        `json:"path"`
	RequestTimeout  pgtype.Int4        `json:"request_timeout"`
	LogLimitBlocks  pgtype.Int4        `json:"log_limit_blocks"`
	AllowedMethods  []string           `json:"allowed_methods"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Deleted         pgtype.Bool        `json:"deleted"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ChainAltruists  []byte             `json:"chain_altruists"`
	ChainChecks     []byte             `json:"chain_checks"`
	AliasDomainsMap []byte             `json:"alias_domains_map"`
}

func (q *Queries) SelectChain(ctx context.Context, id types.RelayChainID) (SelectChainRow, error) {
	row := q.db.QueryRow(ctx, selectChain, id)
	var i SelectChainRow
	err := row.Scan(
		&i.ID,
		&i.Blockchain,
		&i.Description,
		&i.EnforceResult,
		&i.Ticker,
		&i.Path,
		&i.RequestTimeout,
		&i.LogLimitBlocks,
		&i.AllowedMethods,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.ChainAltruists,
		&i.ChainChecks,
		&i.AliasDomainsMap,
	)
	return i, err
}

const selectChains = `-- name: SelectChains :many
SELECT c.id, c.blockchain, c.description, c.enforce_result, c.ticker, c.path, c.request_timeout, c.log_limit_blocks, c.allowed_methods, c.active, c.created_at, c.updated_at, c.deleted, c.deleted_at,
    COALESCE(
        json_agg(DISTINCT ca) FILTER (
            WHERE ca.id IS NOT NULL
        ),
        '[]'
    )::json AS chain_altruists,
    COALESCE(
        json_agg(DISTINCT cc) FILTER (
            WHERE cc.id IS NOT NULL
        ),
        '[]'
    )::json AS chain_checks,
    COALESCE(
        json_object_agg(COALESCE(cga.alias, 'null'), cga.domains) FILTER (
            WHERE cga.alias IS NOT NULL
        ),
        '{}'
    )::json AS alias_domains_map
FROM chains c
    LEFT JOIN chain_altruists ca ON c.id = ca.chain_id
    LEFT JOIN chain_checks cc ON c.id = cc.chain_id
    LEFT JOIN chain_alias_domains cga ON c.id = cga.chain_id
WHERE (
        $1::BOOLEAN
        OR c.deleted = false
    )
GROUP BY c.id
`

type SelectChainsRow struct {
	ID              types.RelayChainID `json:"id"`
	Blockchain      pgtype.Text        `json:"blockchain"`
	Description     pgtype.Text        `json:"description"`
	EnforceResult   pgtype.Text        `json:"enforce_result"`
	Ticker          pgtype.Text        `json:"ticker"`
	Path            pgtype.Text        `json:"path"`
	RequestTimeout  pgtype.Int4        `json:"request_timeout"`
	LogLimitBlocks  pgtype.Int4        `json:"log_limit_blocks"`
	AllowedMethods  []string           `json:"allowed_methods"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Deleted         pgtype.Bool        `json:"deleted"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ChainAltruists  []byte             `json:"chain_altruists"`
	ChainChecks     []byte             `json:"chain_checks"`
	AliasDomainsMap []byte             `json:"alias_domains_map"`
}

func (q *Queries) SelectChains(ctx context.Context, includeDeleted bool) ([]SelectChainsRow, error) {
	rows, err := q.db.Query(ctx, selectChains, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectChainsRow
	for rows.Next() {
		var i SelectChainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Blockchain,
			&i.Description,
			&i.EnforceResult,
			&i.Ticker,
			&i.Path,
			&i.RequestTimeout,
			&i.LogLimitBlocks,
			&i.AllowedMethods,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
			&i.ChainAltruists,
			&i.ChainChecks,
			&i.AliasDomainsMap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGigastakeApplications = `-- name: SelectGigastakeApplications :many
SELECT ga.id,
    ga.name,
    ARRAY_AGG(cga.chain_id)::VARCHAR [] AS chain_ids,
    ga.created_at,
    ga.updated_at,
    ga.deleted,
    ga.address,
    ga.public_key,
    ga.client_public_key,
    ga.signature,
    ga.version
FROM gigastake_applications AS ga
    LEFT JOIN chains_gigastake_applications AS cga ON ga.id = cga.gigastake_application_id
GROUP BY ga.id,
    ga.name,
    ga.created_at,
    ga.updated_at,
    ga.deleted,
    ga.address,
    ga.public_key,
    ga.client_public_key,
    ga.signature,
    ga.version
`

type SelectGigastakeApplicationsRow struct {
	ID              types.GigastakeAppID `json:"id"`
	Name            string               `json:"name"`
	ChainIDs        []string             `json:"chain_ids"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
	Deleted         bool                 `json:"deleted"`
	Address         string               `json:"address"`
	PublicKey       string               `json:"public_key"`
	ClientPublicKey string               `json:"client_public_key"`
	Signature       string               `json:"signature"`
	Version         string               `json:"version"`
}

func (q *Queries) SelectGigastakeApplications(ctx context.Context) ([]SelectGigastakeApplicationsRow, error) {
	rows, err := q.db.Query(ctx, selectGigastakeApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectGigastakeApplicationsRow
	for rows.Next() {
		var i SelectGigastakeApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChainIDs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.Address,
			&i.PublicKey,
			&i.ClientPublicKey,
			&i.Signature,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGlobalBlockedContract = `-- name: SelectGlobalBlockedContract :many
SELECT id,
    blocked_address
FROM global_blocked_contracts
WHERE active = true
`

type SelectGlobalBlockedContractRow struct {
	ID             int32                `json:"id"`
	BlockedAddress types.BlockedAddress `json:"blocked_address"`
}

func (q *Queries) SelectGlobalBlockedContract(ctx context.Context) ([]SelectGlobalBlockedContractRow, error) {
	rows, err := q.db.Query(ctx, selectGlobalBlockedContract)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectGlobalBlockedContractRow
	for rows.Next() {
		var i SelectGlobalBlockedContractRow
		if err := rows.Scan(&i.ID, &i.BlockedAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPlans = `-- name: SelectPlans :many
SELECT plan_type,
    chain_ids,
    monthly_relay_limit,
    throughput_limit,
    application_limit,
    created_at,
    daily_limit
FROM pay_plans
`

type SelectPlansRow struct {
	PlanType          types.PayPlanType  `json:"plan_type"`
	ChainIDs          []string           `json:"chain_ids"`
	MonthlyRelayLimit int32              `json:"monthly_relay_limit"`
	ThroughputLimit   int32              `json:"throughput_limit"`
	ApplicationLimit  int32              `json:"application_limit"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DailyLimit        pgtype.Int4        `json:"daily_limit"`
}

func (q *Queries) SelectPlans(ctx context.Context) ([]SelectPlansRow, error) {
	rows, err := q.db.Query(ctx, selectPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPlansRow
	for rows.Next() {
		var i SelectPlansRow
		if err := rows.Scan(
			&i.PlanType,
			&i.ChainIDs,
			&i.MonthlyRelayLimit,
			&i.ThroughputLimit,
			&i.ApplicationLimit,
			&i.CreatedAt,
			&i.DailyLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPortalApplications = `-- name: SelectPortalApplications :many
WITH aats_agg AS (
    SELECT paa.portal_application_id,
        json_object_agg(
            paa.id,
            json_build_object(
                'address',
                paa.address,
                'public_key',
                paa.public_key,
                'client_public_key',
                paa.client_public_key,
                'signature',
                paa.signature,
                'version',
                paa.version
            )
        ) AS aats
    FROM portal_application_aats paa
    GROUP BY paa.portal_application_id
),
notifications_agg AS (
    SELECT pn.application_id,
        json_object_agg(
            pn.type,
            json_build_object(
                'type',
                pn.type,
                'active',
                pn.active,
                'destination',
                pn.destination,
                'trigger',
                pn.trigger,
                'events',
                (
                    SELECT json_object_agg(
                            event,
                            true
                        )
                    FROM (
                            SELECT unnest(pn.events) AS event
                        ) subquery
                    WHERE event IS NOT NULL
                )
            )
        ) AS notifications
    FROM portal_application_notifications pn
    GROUP BY pn.application_id
),
whitelists_agg AS (
    SELECT paw.application_id,
        json_agg(
            json_build_object(
                'type',
                paw.type,
                'value',
                paw.value,
                'chain_id',
                paw.chain_id
            )
        ) AS whitelists
    FROM portal_application_whitelists paw
    GROUP BY paw.application_id
)
SELECT p.id, p.account_id, p.name, p.created_at, p.updated_at, p.deleted, p.deleted_at, p.request_timeout, p.first_date_surpassed, p.plan_type, p.daily_limit, p.custom_limit,
    pas.secret_key,
    pas.secret_key_required,
    pas.monthly_relay_limit,
    pas.environment,
    COALESCE(aats_agg.aats, '[]'::json) AS aats,
    COALESCE(notifications_agg.notifications, '[]'::json) AS notifications,
    COALESCE(whitelists_agg.whitelists, '[]'::json) AS whitelists
FROM portal_applications p
    LEFT JOIN portal_application_settings pas ON p.id = pas.application_id
    LEFT JOIN aats_agg ON p.id = aats_agg.portal_application_id
    LEFT JOIN notifications_agg ON p.id = notifications_agg.application_id
    LEFT JOIN whitelists_agg ON p.id = whitelists_agg.application_id
WHERE (
        $1::BOOLEAN
        OR p.deleted = false
    )
`

type SelectPortalApplicationsRow struct {
	ID                 types.PortalAppID  `json:"id"`
	AccountID          pgtype.Text        `json:"account_id"`
	Name               string             `json:"name"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Deleted            bool               `json:"deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	RequestTimeout     pgtype.Int4        `json:"request_timeout"`
	FirstDateSurpassed pgtype.Timestamptz `json:"first_date_surpassed"`
	PlanType           types.PayPlanType  `json:"plan_type"`
	DailyLimit         pgtype.Int4        `json:"daily_limit"`
	CustomLimit        pgtype.Int4        `json:"custom_limit"`
	SecretKey          pgtype.Text        `json:"secret_key"`
	SecretKeyRequired  pgtype.Bool        `json:"secret_key_required"`
	MonthlyRelayLimit  pgtype.Int4        `json:"monthly_relay_limit"`
	Environment        NullEnvironment    `json:"environment"`
	AATs               []byte             `json:"aats"`
	Notifications      []byte             `json:"notifications"`
	Whitelists         []byte             `json:"whitelists"`
}

func (q *Queries) SelectPortalApplications(ctx context.Context, dollar_1 bool) ([]SelectPortalApplicationsRow, error) {
	rows, err := q.db.Query(ctx, selectPortalApplications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPortalApplicationsRow
	for rows.Next() {
		var i SelectPortalApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
			&i.RequestTimeout,
			&i.FirstDateSurpassed,
			&i.PlanType,
			&i.DailyLimit,
			&i.CustomLimit,
			&i.SecretKey,
			&i.SecretKeyRequired,
			&i.MonthlyRelayLimit,
			&i.Environment,
			&i.AATs,
			&i.Notifications,
			&i.Whitelists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserIDs = `-- name: SelectUserIDs :many
SELECT user_id,
    provider_user_id
FROM user_auth_providers
`

type SelectUserIDsRow struct {
	UserID         types.UserID         `json:"user_id"`
	ProviderUserID types.ProviderUserID `json:"provider_user_id"`
}

func (q *Queries) SelectUserIDs(ctx context.Context) ([]SelectUserIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserIDsRow
	for rows.Next() {
		var i SelectUserIDsRow
		if err := rows.Scan(&i.UserID, &i.ProviderUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserPermissions = `-- name: SelectUserPermissions :many
SELECT aua.user_id,
    aua.role_name,
    aua.owner,
    ur.permissions::permissions [] AS permissions,
    CASE
        WHEN aua.owner THEN array_agg(pa.id)::VARCHAR []
        ELSE ARRAY [aua.portal_application_id]::VARCHAR []
    END AS portal_application_ids
FROM account_user_access AS aua
    LEFT JOIN user_roles AS ur ON aua.role_name = ur.role_name
    LEFT JOIN portal_applications AS pa ON aua.account_id = pa.account_id
WHERE aua.accepted = true
    AND aua.user_id IS NOT NULL
    AND pa.id IS NOT NULL
GROUP BY aua.user_id,
    aua.role_name,
    aua.owner,
    ur.permissions,
    aua.portal_application_id
`

type SelectUserPermissionsRow struct {
	UserID               types.UserID        `json:"user_id"`
	RoleName             types.RoleName      `json:"role_name"`
	Owner                bool                `json:"owner"`
	Permissions          []types.Permissions `json:"permissions"`
	PortalApplicationIDs []string            `json:"portal_application_ids"`
}

func (q *Queries) SelectUserPermissions(ctx context.Context) ([]SelectUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, selectUserPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserPermissionsRow
	for rows.Next() {
		var i SelectUserPermissionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleName,
			&i.Owner,
			&i.Permissions,
			&i.PortalApplicationIDs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGlobalBlockedContractActive = `-- name: SetGlobalBlockedContractActive :one
UPDATE global_blocked_contracts
SET active = $2,
    updated_at = $3
WHERE blocked_address = $1
RETURNING id
`

type SetGlobalBlockedContractActiveParams struct {
	BlockedAddress types.BlockedAddress `json:"blocked_address"`
	Active         bool                 `json:"active"`
	UpdatedAt      pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) SetGlobalBlockedContractActive(ctx context.Context, arg SetGlobalBlockedContractActiveParams) (int32, error) {
	row := q.db.QueryRow(ctx, setGlobalBlockedContractActive, arg.BlockedAddress, arg.Active, arg.UpdatedAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const transferOwnerCreateRows = `-- name: TransferOwnerCreateRows :exec
WITH updated_user AS (
    UPDATE users
    SET email = users.email
    WHERE id = $4::VARCHAR(24)
),
insert_old_owner_admin_rows AS (
    INSERT INTO account_user_access (
            portal_application_id,
            user_id,
            account_id,
            role_name,
            owner,
            accepted,
            created_at,
            updated_at
        )
    SELECT DISTINCT on (pa.id) pa.id,
        $5::VARCHAR(24),
        aua.account_id,
        'ADMIN',
        false,
        true,
        aua.created_at,
        aua.updated_at
    FROM account_user_access AS aua
        JOIN portal_applications AS pa ON aua.account_id = pa.account_id
    WHERE aua.account_id = $1
        AND NOT EXISTS (
            SELECT 1
            FROM account_user_access
            WHERE user_id = $5::VARCHAR(24)
                AND portal_application_id = pa.id
        )
),
insert_new_owner_row AS (
    INSERT INTO account_user_access (
            user_id,
            account_id,
            role_name,
            owner,
            accepted,
            created_at,
            updated_at
        )
    SELECT $4::VARCHAR(24),
        $1,
        'OWNER',
        true,
        true,
        $2,
        $3
)
SELECT 1
`

type TransferOwnerCreateRowsParams struct {
	AccountID  types.AccountID    `json:"account_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	NewOwnerID string             `json:"new_owner_id"`
	OldOwnerID string             `json:"old_owner_id"`
}

func (q *Queries) TransferOwnerCreateRows(ctx context.Context, arg TransferOwnerCreateRowsParams) error {
	_, err := q.db.Exec(ctx, transferOwnerCreateRows,
		arg.AccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NewOwnerID,
		arg.OldOwnerID,
	)
	return err
}

const transferOwnerDeleteOldRows = `-- name: TransferOwnerDeleteOldRows :one
WITH delete_old_owner_row AS (
    DELETE FROM account_user_access
    WHERE account_user_access.account_id = $1
        AND role_name = 'OWNER'
    RETURNING user_id
),
delete_new_owner_non_owner_rows AS (
    DELETE FROM account_user_access
    WHERE account_user_access.account_id = $1
        AND user_id = $2::VARCHAR(24)
        AND role_name <> 'OWNER'
)
SELECT user_id
FROM delete_old_owner_row
`

type TransferOwnerDeleteOldRowsParams struct {
	AccountID  types.AccountID `json:"account_id"`
	NewOwnerID string          `json:"new_owner_id"`
}

func (q *Queries) TransferOwnerDeleteOldRows(ctx context.Context, arg TransferOwnerDeleteOldRowsParams) (string, error) {
	row := q.db.QueryRow(ctx, transferOwnerDeleteOldRows, arg.AccountID, arg.NewOwnerID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const updateAccountFields = `-- name: UpdateAccountFields :exec
UPDATE accounts
SET plan_type = COALESCE($1, plan_type),
    partner_chain_ids = COALESCE($2, partner_chain_ids),
    partner_throughput_limit = COALESCE($3, partner_throughput_limit),
    partner_application_limit = COALESCE($4, partner_application_limit),
    updated_at = $5
WHERE id = $6
`

type UpdateAccountFieldsParams struct {
	PlanType                types.PayPlanType  `json:"plan_type"`
	PartnerChainIDs         []string           `json:"partner_chain_ids"`
	PartnerThroughputLimit  pgtype.Int4        `json:"partner_throughput_limit"`
	PartnerApplicationLimit pgtype.Int4        `json:"partner_application_limit"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ID                      types.AccountID    `json:"id"`
}

func (q *Queries) UpdateAccountFields(ctx context.Context, arg UpdateAccountFieldsParams) error {
	_, err := q.db.Exec(ctx, updateAccountFields,
		arg.PlanType,
		arg.PartnerChainIDs,
		arg.PartnerThroughputLimit,
		arg.PartnerApplicationLimit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAccountUserRole = `-- name: UpdateAccountUserRole :exec
UPDATE account_user_access
SET role_name = $3,
    updated_at = $4
WHERE portal_application_id = $1
    AND user_id = $2
`

type UpdateAccountUserRoleParams struct {
	PortalApplicationID types.PortalAppID  `json:"portal_application_id"`
	UserID              types.UserID       `json:"user_id"`
	RoleName            types.RoleName     `json:"role_name"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccountUserRole(ctx context.Context, arg UpdateAccountUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateAccountUserRole,
		arg.PortalApplicationID,
		arg.UserID,
		arg.RoleName,
		arg.UpdatedAt,
	)
	return err
}

const updateChain = `-- name: UpdateChain :one
UPDATE chains
SET blockchain = COALESCE($2, chains.blockchain),
    description = COALESCE($3, chains.description),
    enforce_result = COALESCE($4, chains.enforce_result),
    path = COALESCE($5, chains.path),
    ticker = COALESCE($6, chains.ticker),
    request_timeout = COALESCE($7, chains.request_timeout),
    log_limit_blocks = COALESCE($8, chains.log_limit_blocks),
    allowed_methods = COALESCE($9, chains.allowed_methods),
    updated_at = $10
WHERE id = $1
RETURNING id
`

type UpdateChainParams struct {
	ID             types.RelayChainID `json:"id"`
	Blockchain     pgtype.Text        `json:"blockchain"`
	Description    pgtype.Text        `json:"description"`
	EnforceResult  pgtype.Text        `json:"enforce_result"`
	Path           pgtype.Text        `json:"path"`
	Ticker         pgtype.Text        `json:"ticker"`
	RequestTimeout pgtype.Int4        `json:"request_timeout"`
	LogLimitBlocks pgtype.Int4        `json:"log_limit_blocks"`
	AllowedMethods []string           `json:"allowed_methods"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateChain(ctx context.Context, arg UpdateChainParams) (types.RelayChainID, error) {
	row := q.db.QueryRow(ctx, updateChain,
		arg.ID,
		arg.Blockchain,
		arg.Description,
		arg.EnforceResult,
		arg.Path,
		arg.Ticker,
		arg.RequestTimeout,
		arg.LogLimitBlocks,
		arg.AllowedMethods,
		arg.UpdatedAt,
	)
	var id types.RelayChainID
	err := row.Scan(&id)
	return id, err
}

const updateChainActive = `-- name: UpdateChainActive :one
UPDATE chains
SET active = $2,
    updated_at = $3
WHERE id = $1
RETURNING active
`

type UpdateChainActiveParams struct {
	ID        types.RelayChainID `json:"id"`
	Active    bool               `json:"active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateChainActive(ctx context.Context, arg UpdateChainActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, updateChainActive, arg.ID, arg.Active, arg.UpdatedAt)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const updateDeletePortalAppNotification = `-- name: UpdateDeletePortalAppNotification :exec
DELETE FROM portal_application_notifications
WHERE application_id = $1
    and type = $2
`

type UpdateDeletePortalAppNotificationParams struct {
	ApplicationID types.PortalAppID      `json:"application_id"`
	Type          types.NotificationType `json:"type"`
}

func (q *Queries) UpdateDeletePortalAppNotification(ctx context.Context, arg UpdateDeletePortalAppNotificationParams) error {
	_, err := q.db.Exec(ctx, updateDeletePortalAppNotification, arg.ApplicationID, arg.Type)
	return err
}

const updateDeleteWhitelists = `-- name: UpdateDeleteWhitelists :exec
DELETE FROM portal_application_whitelists
WHERE (
        type IN ('methods', 'contracts')
        AND application_id = $1
        AND NOT EXISTS (
            SELECT 1
            FROM unnest($2::whitelist_type []) t1(type),
                unnest($3::VARCHAR []) t2(value),
                unnest($4::VARCHAR []) t3(chain_id)
            WHERE t1.type = portal_application_whitelists.type
                AND t2.value = portal_application_whitelists.value
                AND t3.chain_id = portal_application_whitelists.chain_id
        )
    )
    OR (
        type IN ('blockchains', 'origins', 'userAgents')
        AND application_id = $1
        AND NOT EXISTS (
            SELECT 1
            FROM unnest($2::whitelist_type []) t1(type),
                unnest($3::VARCHAR []) t2(value)
            WHERE t1.type = portal_application_whitelists.type
                AND t2.value = portal_application_whitelists.value
        )
    )
`

type UpdateDeleteWhitelistsParams struct {
	ApplicationID types.PortalAppID     `json:"application_id"`
	Types         []types.WhitelistType `json:"types"`
	Values        []string              `json:"values"`
	ChainIDs      []string              `json:"chain_ids"`
}

func (q *Queries) UpdateDeleteWhitelists(ctx context.Context, arg UpdateDeleteWhitelistsParams) error {
	_, err := q.db.Exec(ctx, updateDeleteWhitelists,
		arg.ApplicationID,
		arg.Types,
		arg.Values,
		arg.ChainIDs,
	)
	return err
}

const updateFirstDatesSurpassed = `-- name: UpdateFirstDatesSurpassed :exec
UPDATE portal_applications
SET first_date_surpassed = $1
WHERE id = ANY ($2::VARCHAR [])
`

type UpdateFirstDatesSurpassedParams struct {
	FirstDateSurpassed pgtype.Timestamptz `json:"first_date_surpassed"`
	PortalAppIds       []string           `json:"portal_app_ids"`
}

func (q *Queries) UpdateFirstDatesSurpassed(ctx context.Context, arg UpdateFirstDatesSurpassedParams) error {
	_, err := q.db.Exec(ctx, updateFirstDatesSurpassed, arg.FirstDateSurpassed, arg.PortalAppIds)
	return err
}

const updateGigastakeAppNameAndChainIDs = `-- name: UpdateGigastakeAppNameAndChainIDs :exec
WITH updated_gigastake_application AS (
    UPDATE gigastake_applications
    SET name = $2,
        updated_at = $3
    WHERE id = $1
    RETURNING id
),
inserted AS (
    INSERT INTO chains_gigastake_applications (chain_id, gigastake_application_id)
    SELECT unnest($4::VARCHAR []),
        updated_gigastake_application.id
    FROM updated_gigastake_application ON CONFLICT (chain_id, gigastake_application_id) DO NOTHING
)
DELETE FROM chains_gigastake_applications
WHERE gigastake_application_id IN (
        SELECT id
        FROM updated_gigastake_application
    )
    AND chain_id NOT IN (
        SELECT unnest($4::VARCHAR [])
    )
`

type UpdateGigastakeAppNameAndChainIDsParams struct {
	ID        types.GigastakeAppID `json:"id"`
	Name      string               `json:"name"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
	ChainIDs  []string             `json:"chain_ids"`
}

func (q *Queries) UpdateGigastakeAppNameAndChainIDs(ctx context.Context, arg UpdateGigastakeAppNameAndChainIDsParams) error {
	_, err := q.db.Exec(ctx, updateGigastakeAppNameAndChainIDs,
		arg.ID,
		arg.Name,
		arg.UpdatedAt,
		arg.ChainIDs,
	)
	return err
}

const updateInsertWhitelists = `-- name: UpdateInsertWhitelists :exec
INSERT INTO portal_application_whitelists (
        application_id,
        type,
        chain_id,
        value,
        created_at
    )
VALUES(
        $1,
        unnest($2::whitelist_type []),
        NULLIF(unnest($3::VARCHAR []), ''),
        unnest($4::VARCHAR []),
        $5::TIMESTAMPTZ
    ) ON CONFLICT (application_id, chain_id, type, value) DO NOTHING
`

type UpdateInsertWhitelistsParams struct {
	ApplicationID types.PortalAppID     `json:"application_id"`
	Types         []types.WhitelistType `json:"types"`
	ChainIDs      []string              `json:"chain_ids"`
	Values        []string              `json:"values"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
}

func (q *Queries) UpdateInsertWhitelists(ctx context.Context, arg UpdateInsertWhitelistsParams) error {
	_, err := q.db.Exec(ctx, updateInsertWhitelists,
		arg.ApplicationID,
		arg.Types,
		arg.ChainIDs,
		arg.Values,
		arg.CreatedAt,
	)
	return err
}

const updatePortalAppFields = `-- name: UpdatePortalAppFields :exec
UPDATE portal_applications
SET name = COALESCE(NULLIF($5::VARCHAR, ''), name),
    plan_type = COALESCE(NULLIF($6::VARCHAR, ''), plan_type),
    daily_limit = COALESCE($2, daily_limit),
    custom_limit = COALESCE($3, custom_limit),
    updated_at = $4
WHERE id = $1
`

type UpdatePortalAppFieldsParams struct {
	ID          types.PortalAppID  `json:"id"`
	DailyLimit  pgtype.Int4        `json:"daily_limit"`
	CustomLimit pgtype.Int4        `json:"custom_limit"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        string             `json:"name"`
	PlanType    string             `json:"plan_type"`
}

func (q *Queries) UpdatePortalAppFields(ctx context.Context, arg UpdatePortalAppFieldsParams) error {
	_, err := q.db.Exec(ctx, updatePortalAppFields,
		arg.ID,
		arg.DailyLimit,
		arg.CustomLimit,
		arg.UpdatedAt,
		arg.Name,
		arg.PlanType,
	)
	return err
}

const updatePortalAppSettings = `-- name: UpdatePortalAppSettings :exec
UPDATE portal_application_settings
SET secret_key = COALESCE($2, secret_key),
    secret_key_required = COALESCE($3, secret_key_required),
    monthly_relay_limit = COALESCE($4, monthly_relay_limit),
    environment = COALESCE($5, environment),
    favorited_chain_ids = COALESCE($6, favorited_chain_ids),
    updated_at = COALESCE($7, updated_at)
WHERE application_id = $1
`

type UpdatePortalAppSettingsParams struct {
	ApplicationID     types.PortalAppID  `json:"application_id"`
	SecretKey         pgtype.Text        `json:"secret_key"`
	SecretKeyRequired pgtype.Bool        `json:"secret_key_required"`
	MonthlyRelayLimit int32              `json:"monthly_relay_limit"`
	Environment       types.Environment  `json:"environment"`
	FavoritedChainIDs []string           `json:"favorited_chain_ids"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePortalAppSettings(ctx context.Context, arg UpdatePortalAppSettingsParams) error {
	_, err := q.db.Exec(ctx, updatePortalAppSettings,
		arg.ApplicationID,
		arg.SecretKey,
		arg.SecretKeyRequired,
		arg.MonthlyRelayLimit,
		arg.Environment,
		arg.FavoritedChainIDs,
		arg.UpdatedAt,
	)
	return err
}

const updateUpsertPortalAppNotification = `-- name: UpdateUpsertPortalAppNotification :exec
INSERT INTO portal_application_notifications (
        application_id,
        type,
        active,
        destination,
        trigger,
        events,
        updated_at
    )
SELECT $1,
    $3::notification_type,
    $4::BOOLEAN,
    $5::VARCHAR(255),
    $6::VARCHAR(255),
    $7::notification_event [],
    $2
WHERE $4 IS true ON CONFLICT (application_id, type) DO
UPDATE
SET active = EXCLUDED.active,
    destination = EXCLUDED.destination,
    trigger = EXCLUDED.trigger,
    events = EXCLUDED.events,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.active IS true
`

type UpdateUpsertPortalAppNotificationParams struct {
	ApplicationID types.PortalAppID         `json:"application_id"`
	UpdatedAt     pgtype.Timestamptz        `json:"updated_at"`
	Type          types.NotificationType    `json:"type"`
	Active        bool                      `json:"active"`
	Destination   string                    `json:"destination"`
	Trigger       string                    `json:"trigger"`
	Events        []types.NotificationEvent `json:"events"`
}

func (q *Queries) UpdateUpsertPortalAppNotification(ctx context.Context, arg UpdateUpsertPortalAppNotificationParams) error {
	_, err := q.db.Exec(ctx, updateUpsertPortalAppNotification,
		arg.ApplicationID,
		arg.UpdatedAt,
		arg.Type,
		arg.Active,
		arg.Destination,
		arg.Trigger,
		arg.Events,
	)
	return err
}

const updateUserAcceptedInvite = `-- name: UpdateUserAcceptedInvite :exec
WITH inserted_provider AS (
    INSERT INTO user_auth_providers (
            user_id,
            type,
            provider,
            provider_user_id,
            federated
        )
    VALUES ($1, $2, $3, $4, $5)
    RETURNING user_id
),
updated_access AS (
    UPDATE account_user_access
    SET accepted = true
    WHERE user_id = (
            SELECT user_id
            FROM inserted_provider
        )
        AND portal_application_id = $6
)
UPDATE users
SET signed_up = true
WHERE id = (
        SELECT user_id
        FROM inserted_provider
    )
`

type UpdateUserAcceptedInviteParams struct {
	UserID              types.UserID         `json:"user_id"`
	Type                types.AuthType       `json:"type"`
	Provider            types.AuthProvider   `json:"provider"`
	ProviderUserID      types.ProviderUserID `json:"provider_user_id"`
	Federated           bool                 `json:"federated"`
	PortalApplicationID types.PortalAppID    `json:"portal_application_id"`
}

func (q *Queries) UpdateUserAcceptedInvite(ctx context.Context, arg UpdateUserAcceptedInviteParams) error {
	_, err := q.db.Exec(ctx, updateUserAcceptedInvite,
		arg.UserID,
		arg.Type,
		arg.Provider,
		arg.ProviderUserID,
		arg.Federated,
		arg.PortalApplicationID,
	)
	return err
}

const upsertAccountIntegrations = `-- name: UpsertAccountIntegrations :one
INSERT INTO account_integrations (
        account_id,
        covalent_api_key_free,
        covalent_api_key_paid,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5) ON CONFLICT (account_id) DO
UPDATE
SET covalent_api_key_free = CASE
        WHEN EXCLUDED.covalent_api_key_free IS NOT NULL THEN EXCLUDED.covalent_api_key_free
        ELSE account_integrations.covalent_api_key_free
    END,
    covalent_api_key_paid = CASE
        WHEN EXCLUDED.covalent_api_key_paid IS NOT NULL THEN EXCLUDED.covalent_api_key_paid
        ELSE account_integrations.covalent_api_key_paid
    END,
    created_at = CASE
        WHEN EXCLUDED.created_at IS NOT NULL THEN EXCLUDED.created_at
        ELSE account_integrations.created_at
    END,
    updated_at = EXCLUDED.updated_at
RETURNING id, account_id, covalent_api_key_free, covalent_api_key_paid, created_at, updated_at
`

type UpsertAccountIntegrationsParams struct {
	AccountID          types.AccountID    `json:"account_id"`
	CovalentAPIKeyFree pgtype.Text        `json:"covalent_api_key_free"`
	CovalentAPIKeyPaid pgtype.Text        `json:"covalent_api_key_paid"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAccountIntegrations(ctx context.Context, arg UpsertAccountIntegrationsParams) (AccountIntegration, error) {
	row := q.db.QueryRow(ctx, upsertAccountIntegrations,
		arg.AccountID,
		arg.CovalentAPIKeyFree,
		arg.CovalentAPIKeyPaid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AccountIntegration
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CovalentAPIKeyFree,
		&i.CovalentAPIKeyPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChainAliasDomains = `-- name: UpsertChainAliasDomains :exec
INSERT INTO chain_alias_domains (
        chain_id,
        alias,
        domains,
        updated_at
    )
VALUES ($1, $2, $3, $4) ON CONFLICT (chain_id, alias) DO
UPDATE
SET domains = COALESCE(
        EXCLUDED.domains,
        chain_alias_domains.domains
    ),
    updated_at = EXCLUDED.updated_at
`

type UpsertChainAliasDomainsParams struct {
	ChainID   types.RelayChainID `json:"chain_id"`
	Alias     types.ChainAlias   `json:"alias"`
	Domains   []string           `json:"domains"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertChainAliasDomains(ctx context.Context, arg UpsertChainAliasDomainsParams) error {
	_, err := q.db.Exec(ctx, upsertChainAliasDomains,
		arg.ChainID,
		arg.Alias,
		arg.Domains,
		arg.UpdatedAt,
	)
	return err
}

const upsertChainAltruist = `-- name: UpsertChainAltruist :exec
INSERT INTO chain_altruists (
        chain_id,
        url,
        auth,
        auth_type,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (chain_id, url) DO
UPDATE
SET auth = COALESCE(EXCLUDED.auth, chain_altruists.auth),
    auth_type = COALESCE(EXCLUDED.auth_type, chain_altruists.auth_type),
    updated_at = EXCLUDED.updated_at
`

type UpsertChainAltruistParams struct {
	ChainID   types.RelayChainID  `json:"chain_id"`
	URL       types.AltruistURL   `json:"url"`
	Auth      pgtype.Text         `json:"auth"`
	AuthType  types.ChainAuthType `json:"auth_type"`
	CreatedAt pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt pgtype.Timestamptz  `json:"updated_at"`
}

func (q *Queries) UpsertChainAltruist(ctx context.Context, arg UpsertChainAltruistParams) error {
	_, err := q.db.Exec(ctx, upsertChainAltruist,
		arg.ChainID,
		arg.URL,
		arg.Auth,
		arg.AuthType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertChainCheck = `-- name: UpsertChainCheck :exec
INSERT INTO chain_checks (
        chain_id,
        type,
        payload,
        result_key,
        allowance,
        evm_chain_id,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    ) ON CONFLICT (chain_id, type) DO
UPDATE
SET payload = COALESCE(EXCLUDED.payload, chain_checks.payload),
    result_key = COALESCE(EXCLUDED.result_key, chain_checks.result_key),
    allowance = COALESCE(EXCLUDED.allowance, chain_checks.allowance),
    evm_chain_id = COALESCE(EXCLUDED.evm_chain_id, chain_checks.evm_chain_id),
    updated_at = EXCLUDED.updated_at
`

type UpsertChainCheckParams struct {
	ChainID    types.RelayChainID   `json:"chain_id"`
	Type       types.ChainCheckType `json:"type"`
	Payload    pgtype.Text          `json:"payload"`
	ResultKey  pgtype.Text          `json:"result_key"`
	Allowance  pgtype.Int4          `json:"allowance"`
	EVMChainID pgtype.Int4          `json:"evm_chain_id"`
	CreatedAt  pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) UpsertChainCheck(ctx context.Context, arg UpsertChainCheckParams) error {
	_, err := q.db.Exec(ctx, upsertChainCheck,
		arg.ChainID,
		arg.Type,
		arg.Payload,
		arg.ResultKey,
		arg.Allowance,
		arg.EVMChainID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
