// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package postgresdriver

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const selectPortalApplications = `-- name: SelectPortalApplications :many
SELECT p.id, p.account_id, p.name, p.gigastake, p.application_id, p.request_timeout, p.gigastake_redirect, p.first_date_surpassed, p.created_at, p.updated_at, p.deleted,
    pso.duration,
    pso.sticky_max,
    pso.stickiness,
    pso.origins,
    paa.address,
    paa.public_key,
    paa.private_key,
    paa.client_public_key,
    paa.signature,
    paa.version,
    pas.secret_key,
    pas.secret_key_required,
    pas.monthly_relay_limit,
    pas.environment,
    json_object_agg(
        pn.type,
        json_build_object(
            'active',
            pn.active,
            'destination',
            pn.destination,
            'trigger',
            pn.trigger,
            'events',
            pn.events
        )
    ) AS notifications,
    json_agg(
        json_build_object(
            'type',
            paw.type,
            'value',
            paw.value,
            'blockchain_id',
            paw.blockchain_id
        )
    ) AS whitelists
FROM portal_applications AS p
    LEFT JOIN stickiness_options AS pso ON p.id = pso.application_id
    LEFT JOIN portal_application_aats AS paa ON p.id = paa.application_id
    LEFT JOIN portal_application_settings AS pas ON p.id = pas.application_id
    LEFT JOIN portal_application_notifications AS pn ON p.id = pn.application_id
    LEFT JOIN portal_application_whitelists AS paw ON p.id = paw.application_id
GROUP BY p.id,
    pso.duration,
    pso.sticky_max,
    pso.stickiness,
    pso.origins,
    paa.address,
    paa.public_key,
    paa.private_key,
    paa.client_public_key,
    paa.signature,
    paa.version,
    pas.secret_key,
    pas.secret_key_required,
    pas.monthly_relay_limit,
    pas.environment
`

type SelectPortalApplicationsRow struct {
	ID                 string          `json:"id"`
	AccountID          sql.NullInt64   `json:"accountID"`
	Name               string          `json:"name"`
	Gigastake          bool            `json:"gigastake"`
	ApplicationID      sql.NullString  `json:"applicationID"`
	RequestTimeout     sql.NullInt32   `json:"requestTimeout"`
	GigastakeRedirect  sql.NullBool    `json:"gigastakeRedirect"`
	FirstDateSurpassed sql.NullTime    `json:"firstDateSurpassed"`
	CreatedAt          sql.NullTime    `json:"createdAt"`
	UpdatedAt          sql.NullTime    `json:"updatedAt"`
	Deleted            sql.NullBool    `json:"deleted"`
	Duration           sql.NullString  `json:"duration"`
	StickyMax          sql.NullInt32   `json:"stickyMax"`
	Stickiness         sql.NullBool    `json:"stickiness"`
	Origins            []string        `json:"origins"`
	Address            sql.NullString  `json:"address"`
	PublicKey          sql.NullString  `json:"publicKey"`
	PrivateKey         sql.NullString  `json:"privateKey"`
	ClientPublicKey    sql.NullString  `json:"clientPublicKey"`
	Signature          sql.NullString  `json:"signature"`
	Version            sql.NullString  `json:"version"`
	SecretKey          sql.NullString  `json:"secretKey"`
	SecretKeyRequired  sql.NullBool    `json:"secretKeyRequired"`
	MonthlyRelayLimit  sql.NullInt32   `json:"monthlyRelayLimit"`
	Environment        NullEnvironment `json:"environment"`
	Notifications      json.RawMessage `json:"notifications"`
	Whitelists         json.RawMessage `json:"whitelists"`
}

func (q *Queries) SelectPortalApplications(ctx context.Context) ([]SelectPortalApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectPortalApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPortalApplicationsRow
	for rows.Next() {
		var i SelectPortalApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Gigastake,
			&i.ApplicationID,
			&i.RequestTimeout,
			&i.GigastakeRedirect,
			&i.FirstDateSurpassed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.Duration,
			&i.StickyMax,
			&i.Stickiness,
			pq.Array(&i.Origins),
			&i.Address,
			&i.PublicKey,
			&i.PrivateKey,
			&i.ClientPublicKey,
			&i.Signature,
			&i.Version,
			&i.SecretKey,
			&i.SecretKeyRequired,
			&i.MonthlyRelayLimit,
			&i.Environment,
			&i.Notifications,
			&i.Whitelists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
