// Code generated by mockery v2.15.0. DO NOT EDIT.

package driver

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/pokt-foundation/portal-db/types"
)

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

// AcceptAccountUser provides a mock function with given fields: ctx, email, userID, portalAppID
func (_m *MockDriver) AcceptAccountUser(ctx context.Context, email types.Email, userID types.UserID, portalAppID string) error {
	ret := _m.Called(ctx, email, userID, portalAppID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Email, types.UserID, string) error); ok {
		r0 = rf(ctx, email, userID, portalAppID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivateChain provides a mock function with given fields: ctx, chainID, active
func (_m *MockDriver) ActivateChain(ctx context.Context, chainID types.ChainID, active bool) error {
	ret := _m.Called(ctx, chainID, active)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChainID, bool) error); ok {
		r0 = rf(ctx, chainID, active)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccount provides a mock function with given fields: ctx, account
func (_m *MockDriver) DeleteAccount(ctx context.Context, account types.Account) error {
	ret := _m.Called(ctx, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccountUser provides a mock function with given fields: ctx, email, portalAppID
func (_m *MockDriver) DeleteAccountUser(ctx context.Context, email types.Email, portalAppID types.PortalAppID) error {
	ret := _m.Called(ctx, email, portalAppID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Email, types.PortalAppID) error); ok {
		r0 = rf(ctx, email, portalAppID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGigastakeRedirect provides a mock function with given fields: ctx, chainID, domain
func (_m *MockDriver) DeleteGigastakeRedirect(ctx context.Context, chainID types.ChainID, domain string) error {
	ret := _m.Called(ctx, chainID, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChainID, string) error); ok {
		r0 = rf(ctx, chainID, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePortalUser provides a mock function with given fields: ctx, userID
func (_m *MockDriver) DeletePortalUser(ctx context.Context, userID types.UserID) (types.UserID, error) {
	ret := _m.Called(ctx, userID)

	var r0 types.UserID
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) types.UserID); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(types.UserID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortalUserIDFromProviderID provides a mock function with given fields: ctx, providerUserID
func (_m *MockDriver) GetPortalUserIDFromProviderID(ctx context.Context, providerUserID string) (types.UserID, error) {
	ret := _m.Called(ctx, providerUserID)

	var r0 types.UserID
	if rf, ok := ret.Get(0).(func(context.Context, string) types.UserID); ok {
		r0 = rf(ctx, providerUserID)
	} else {
		r0 = ret.Get(0).(types.UserID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationChannel provides a mock function with given fields:
func (_m *MockDriver) NotificationChannel() <-chan *types.Notification {
	ret := _m.Called()

	var r0 <-chan *types.Notification
	if rf, ok := ret.Get(0).(func() <-chan *types.Notification); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *types.Notification)
		}
	}

	return r0
}

// ReadAccounts provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadAccounts(ctx context.Context, options types.DriverOptions) (map[types.AccountID]*types.Account, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.AccountID]*types.Account
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.AccountID]*types.Account); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.AccountID]*types.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadChains provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadChains(ctx context.Context, options types.DriverOptions) (map[types.ChainID]*types.Chain, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.ChainID]*types.Chain
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.ChainID]*types.Chain); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ChainID]*types.Chain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPlans provides a mock function with given fields: ctx
func (_m *MockDriver) ReadPlans(ctx context.Context) (map[types.PayPlanType]*types.Plan, error) {
	ret := _m.Called(ctx)

	var r0 map[types.PayPlanType]*types.Plan
	if rf, ok := ret.Get(0).(func(context.Context) map[types.PayPlanType]*types.Plan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.PayPlanType]*types.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPortalApps provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadPortalApps(ctx context.Context, options types.DriverOptions) (map[types.PortalAppID]*types.PortalApp, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.PortalAppID]*types.PortalApp
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.PortalAppID]*types.PortalApp); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.PortalAppID]*types.PortalApp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadUserByUserID provides a mock function with given fields: ctx, userID
func (_m *MockDriver) ReadUserByUserID(ctx context.Context, userID types.UserID) (*types.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *types.User
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) *types.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadUserPermissions provides a mock function with given fields: ctx
func (_m *MockDriver) ReadUserPermissions(ctx context.Context) (map[types.UserID]*types.UserPermissions, error) {
	ret := _m.Called(ctx)

	var r0 map[types.UserID]*types.UserPermissions
	if rf, ok := ret.Get(0).(func(context.Context) map[types.UserID]*types.UserPermissions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.UserID]*types.UserPermissions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPortalAppDeleted provides a mock function with given fields: ctx, portalAppID, deletedAt
func (_m *MockDriver) SetPortalAppDeleted(ctx context.Context, portalAppID types.PortalAppID, deletedAt time.Time) error {
	ret := _m.Called(ctx, portalAppID, deletedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalAppID, time.Time) error); ok {
		r0 = rf(ctx, portalAppID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAccountUserRole provides a mock function with given fields: ctx, email, portalAppID, roleName
func (_m *MockDriver) UpdateAccountUserRole(ctx context.Context, email types.Email, portalAppID types.PortalAppID, roleName types.RoleName) error {
	ret := _m.Called(ctx, email, portalAppID, roleName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Email, types.PortalAppID, types.RoleName) error); ok {
		r0 = rf(ctx, email, portalAppID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChain provides a mock function with given fields: ctx, chainID, update
func (_m *MockDriver) UpdateChain(ctx context.Context, chainID types.ChainID, update *types.UpdateChain) error {
	ret := _m.Called(ctx, chainID, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChainID, *types.UpdateChain) error); ok {
		r0 = rf(ctx, chainID, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePortalApp provides a mock function with given fields: ctx, update, updatedAt
func (_m *MockDriver) UpdatePortalApp(ctx context.Context, update types.UpdatePortalApp, updatedAt time.Time) error {
	ret := _m.Called(ctx, update, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdatePortalApp, time.Time) error); ok {
		r0 = rf(ctx, update, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePortalAppsFirstDateSurpassed provides a mock function with given fields: ctx, update
func (_m *MockDriver) UpdatePortalAppsFirstDateSurpassed(ctx context.Context, update *types.UpdateFirstDateSurpassed) error {
	ret := _m.Called(ctx, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.UpdateFirstDateSurpassed) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteAccount provides a mock function with given fields: ctx, account
func (_m *MockDriver) WriteAccount(ctx context.Context, account types.Account) error {
	ret := _m.Called(ctx, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteAccountUser provides a mock function with given fields: ctx, portalAppID, accountUser
func (_m *MockDriver) WriteAccountUser(ctx context.Context, portalAppID types.PortalAppID, accountUser types.AccountUserAccess) error {
	ret := _m.Called(ctx, portalAppID, accountUser)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalAppID, types.AccountUserAccess) error); ok {
		r0 = rf(ctx, portalAppID, accountUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteChain provides a mock function with given fields: ctx, blockchain
func (_m *MockDriver) WriteChain(ctx context.Context, blockchain *types.Chain) (*types.Chain, error) {
	ret := _m.Called(ctx, blockchain)

	var r0 *types.Chain
	if rf, ok := ret.Get(0).(func(context.Context, *types.Chain) *types.Chain); ok {
		r0 = rf(ctx, blockchain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Chain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *types.Chain) error); ok {
		r1 = rf(ctx, blockchain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteGigastakeRedirect provides a mock function with given fields: ctx, redirect
func (_m *MockDriver) WriteGigastakeRedirect(ctx context.Context, redirect *types.GigastakeRedirect) (*types.GigastakeRedirect, error) {
	ret := _m.Called(ctx, redirect)

	var r0 *types.GigastakeRedirect
	if rf, ok := ret.Get(0).(func(context.Context, *types.GigastakeRedirect) *types.GigastakeRedirect); ok {
		r0 = rf(ctx, redirect)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.GigastakeRedirect)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *types.GigastakeRedirect) error); ok {
		r1 = rf(ctx, redirect)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WritePortalApp provides a mock function with given fields: ctx, portalApp, createdAt
func (_m *MockDriver) WritePortalApp(ctx context.Context, portalApp types.PortalApp, createdAt time.Time) (*types.PortalApp, error) {
	ret := _m.Called(ctx, portalApp, createdAt)

	var r0 *types.PortalApp
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalApp, time.Time) *types.PortalApp); ok {
		r0 = rf(ctx, portalApp, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.PortalApp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.PortalApp, time.Time) error); ok {
		r1 = rf(ctx, portalApp, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteUserNewSignUp provides a mock function with given fields: ctx, user, createdAt
func (_m *MockDriver) WriteUserNewSignUp(ctx context.Context, user types.CreateUser, createdAt time.Time) error {
	ret := _m.Called(ctx, user, createdAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.CreateUser, time.Time) error); ok {
		r0 = rf(ctx, user, createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteUserProviderSignedUp provides a mock function with given fields: ctx, userID, user, createdAt
func (_m *MockDriver) WriteUserProviderSignedUp(ctx context.Context, userID types.UserID, user types.CreateUser, createdAt time.Time) (types.UserID, error) {
	ret := _m.Called(ctx, userID, user, createdAt)

	var r0 types.UserID
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.CreateUser, time.Time) types.UserID); ok {
		r0 = rf(ctx, userID, user, createdAt)
	} else {
		r0 = ret.Get(0).(types.UserID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.UserID, types.CreateUser, time.Time) error); ok {
		r1 = rf(ctx, userID, user, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockDriver interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDriver(t mockConstructorTestingTNewMockDriver) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
