// Code generated by mockery v2.32.0. DO NOT EDIT.

package driver

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/pokt-foundation/portal-db/v2/types"
)

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

// DeletePortalUser provides a mock function with given fields: ctx, userID
func (_m *MockDriver) DeletePortalUser(ctx context.Context, userID types.UserID) (types.UserID, error) {
	ret := _m.Called(ctx, userID)

	var r0 types.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) (types.UserID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) types.UserID); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(types.UserID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationChannel provides a mock function with given fields:
func (_m *MockDriver) NotificationChannel() <-chan *types.Notification {
	ret := _m.Called()

	var r0 <-chan *types.Notification
	if rf, ok := ret.Get(0).(func() <-chan *types.Notification); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *types.Notification)
		}
	}

	return r0
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDriver) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAccounts provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadAccounts(ctx context.Context, options types.DriverOptions) (map[types.AccountID]*types.Account, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.AccountID]*types.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) (map[types.AccountID]*types.Account, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.AccountID]*types.Account); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.AccountID]*types.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadBlockedContracts provides a mock function with given fields: ctx
func (_m *MockDriver) ReadBlockedContracts(ctx context.Context) (types.GlobalBlockedContracts, error) {
	ret := _m.Called(ctx)

	var r0 types.GlobalBlockedContracts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.GlobalBlockedContracts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.GlobalBlockedContracts); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(types.GlobalBlockedContracts)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadChains provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadChains(ctx context.Context, options types.DriverOptions) (map[types.RelayChainID]*types.Chain, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.RelayChainID]*types.Chain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) (map[types.RelayChainID]*types.Chain, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.RelayChainID]*types.Chain); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.RelayChainID]*types.Chain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadGigastakeApps provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadGigastakeApps(ctx context.Context, options types.DriverOptions) (map[types.GigastakeAppID]*types.GigastakeApp, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.GigastakeAppID]*types.GigastakeApp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) (map[types.GigastakeAppID]*types.GigastakeApp, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.GigastakeAppID]*types.GigastakeApp); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.GigastakeAppID]*types.GigastakeApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPlans provides a mock function with given fields: ctx
func (_m *MockDriver) ReadPlans(ctx context.Context) (map[types.PayPlanType]*types.Plan, error) {
	ret := _m.Called(ctx)

	var r0 map[types.PayPlanType]*types.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[types.PayPlanType]*types.Plan, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[types.PayPlanType]*types.Plan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.PayPlanType]*types.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPortalApps provides a mock function with given fields: ctx, options
func (_m *MockDriver) ReadPortalApps(ctx context.Context, options types.DriverOptions) (map[types.PortalAppID]*types.PortalApp, error) {
	ret := _m.Called(ctx, options)

	var r0 map[types.PortalAppID]*types.PortalApp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) (map[types.PortalAppID]*types.PortalApp, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.DriverOptions) map[types.PortalAppID]*types.PortalApp); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.PortalAppID]*types.PortalApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.DriverOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadUserByUserID provides a mock function with given fields: ctx, userID
func (_m *MockDriver) ReadUserByUserID(ctx context.Context, userID types.UserID) (*types.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) (*types.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) *types.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadUserIDsMap provides a mock function with given fields: ctx
func (_m *MockDriver) ReadUserIDsMap(ctx context.Context) (map[types.ProviderUserID]types.UserID, error) {
	ret := _m.Called(ctx)

	var r0 map[types.ProviderUserID]types.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[types.ProviderUserID]types.UserID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[types.ProviderUserID]types.UserID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ProviderUserID]types.UserID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadUserPermissions provides a mock function with given fields: ctx
func (_m *MockDriver) ReadUserPermissions(ctx context.Context) (map[types.UserID]*types.UserPermissions, error) {
	ret := _m.Called(ctx)

	var r0 map[types.UserID]*types.UserPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[types.UserID]*types.UserPermissions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[types.UserID]*types.UserPermissions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.UserID]*types.UserPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAccountUser provides a mock function with given fields: ctx, userID, portalAppID, accountID
func (_m *MockDriver) RemoveAccountUser(ctx context.Context, userID types.UserID, portalAppID types.PortalAppID, accountID types.AccountID) error {
	ret := _m.Called(ctx, userID, portalAppID, accountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.PortalAppID, types.AccountID) error); ok {
		r0 = rf(ctx, userID, portalAppID, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveBlockedContract provides a mock function with given fields: ctx, blockedAddress
func (_m *MockDriver) RemoveBlockedContract(ctx context.Context, blockedAddress types.BlockedAddress) error {
	ret := _m.Called(ctx, blockedAddress)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockedAddress) error); ok {
		r0 = rf(ctx, blockedAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAccountDeleted provides a mock function with given fields: ctx, accountID, deletedAt
func (_m *MockDriver) SetAccountDeleted(ctx context.Context, accountID types.AccountID, deletedAt time.Time) error {
	ret := _m.Called(ctx, accountID, deletedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccountID, time.Time) error); ok {
		r0 = rf(ctx, accountID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAccountUserRole provides a mock function with given fields: ctx, updateAccountUser, updatedAt
func (_m *MockDriver) SetAccountUserRole(ctx context.Context, updateAccountUser types.UpdateAccountUserRole, updatedAt time.Time) error {
	ret := _m.Called(ctx, updateAccountUser, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateAccountUserRole, time.Time) error); ok {
		r0 = rf(ctx, updateAccountUser, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetChainActiveStatus provides a mock function with given fields: ctx, chainID, active, updatedAt
func (_m *MockDriver) SetChainActiveStatus(ctx context.Context, chainID types.RelayChainID, active bool, updatedAt time.Time) (bool, error) {
	ret := _m.Called(ctx, chainID, active, updatedAt)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RelayChainID, bool, time.Time) (bool, error)); ok {
		return rf(ctx, chainID, active, updatedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RelayChainID, bool, time.Time) bool); ok {
		r0 = rf(ctx, chainID, active, updatedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RelayChainID, bool, time.Time) error); ok {
		r1 = rf(ctx, chainID, active, updatedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPortalAppDeleted provides a mock function with given fields: ctx, portalAppID, deletedAt
func (_m *MockDriver) SetPortalAppDeleted(ctx context.Context, portalAppID types.PortalAppID, deletedAt time.Time) error {
	ret := _m.Called(ctx, portalAppID, deletedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalAppID, time.Time) error); ok {
		r0 = rf(ctx, portalAppID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAcceptAccountUser provides a mock function with given fields: ctx, acceptAccountUser, updatedAt
func (_m *MockDriver) UpdateAcceptAccountUser(ctx context.Context, acceptAccountUser types.UpdateAcceptAccountUser, updatedAt time.Time) error {
	ret := _m.Called(ctx, acceptAccountUser, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateAcceptAccountUser, time.Time) error); ok {
		r0 = rf(ctx, acceptAccountUser, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAccount provides a mock function with given fields: ctx, update, updatedAt
func (_m *MockDriver) UpdateAccount(ctx context.Context, update types.UpdateAccount, updatedAt time.Time) (*types.Account, error) {
	ret := _m.Called(ctx, update, updatedAt)

	var r0 *types.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateAccount, time.Time) (*types.Account, error)); ok {
		return rf(ctx, update, updatedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateAccount, time.Time) *types.Account); ok {
		r0 = rf(ctx, update, updatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UpdateAccount, time.Time) error); ok {
		r1 = rf(ctx, update, updatedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBlockedContractActive provides a mock function with given fields: ctx, blockedAddress, active, updatedAt
func (_m *MockDriver) UpdateBlockedContractActive(ctx context.Context, blockedAddress types.BlockedAddress, active bool, updatedAt time.Time) error {
	ret := _m.Called(ctx, blockedAddress, active, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockedAddress, bool, time.Time) error); ok {
		r0 = rf(ctx, blockedAddress, active, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChain provides a mock function with given fields: ctx, chain, updatedAt
func (_m *MockDriver) UpdateChain(ctx context.Context, chain types.UpdateChain, updatedAt time.Time) (*types.Chain, error) {
	ret := _m.Called(ctx, chain, updatedAt)

	var r0 *types.Chain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateChain, time.Time) (*types.Chain, error)); ok {
		return rf(ctx, chain, updatedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateChain, time.Time) *types.Chain); ok {
		r0 = rf(ctx, chain, updatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Chain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UpdateChain, time.Time) error); ok {
		r1 = rf(ctx, chain, updatedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGigastakeApp provides a mock function with given fields: ctx, gigastakeApp, updatedAt
func (_m *MockDriver) UpdateGigastakeApp(ctx context.Context, gigastakeApp types.UpdateGigastakeApp, updatedAt time.Time) error {
	ret := _m.Called(ctx, gigastakeApp, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdateGigastakeApp, time.Time) error); ok {
		r0 = rf(ctx, gigastakeApp, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePortalApp provides a mock function with given fields: ctx, update, updatedAt
func (_m *MockDriver) UpdatePortalApp(ctx context.Context, update types.UpdatePortalApp, updatedAt time.Time) error {
	ret := _m.Called(ctx, update, updatedAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UpdatePortalApp, time.Time) error); ok {
		r0 = rf(ctx, update, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePortalAppsFirstDateSurpassed provides a mock function with given fields: ctx, update
func (_m *MockDriver) UpdatePortalAppsFirstDateSurpassed(ctx context.Context, update *types.UpdateFirstDateSurpassed) error {
	ret := _m.Called(ctx, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.UpdateFirstDateSurpassed) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertAccountIntegration provides a mock function with given fields: ctx, integrations
func (_m *MockDriver) UpsertAccountIntegration(ctx context.Context, integrations types.AccountIntegrations) (*types.AccountIntegrations, error) {
	ret := _m.Called(ctx, integrations)

	var r0 *types.AccountIntegrations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccountIntegrations) (*types.AccountIntegrations, error)); ok {
		return rf(ctx, integrations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccountIntegrations) *types.AccountIntegrations); ok {
		r0 = rf(ctx, integrations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccountIntegrations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccountIntegrations) error); ok {
		r1 = rf(ctx, integrations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteAccount provides a mock function with given fields: ctx, creatorID, account, createdAt
func (_m *MockDriver) WriteAccount(ctx context.Context, creatorID types.UserID, account types.Account, createdAt time.Time) (*types.Account, error) {
	ret := _m.Called(ctx, creatorID, account, createdAt)

	var r0 *types.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.Account, time.Time) (*types.Account, error)); ok {
		return rf(ctx, creatorID, account, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.Account, time.Time) *types.Account); ok {
		r0 = rf(ctx, creatorID, account, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID, types.Account, time.Time) error); ok {
		r1 = rf(ctx, creatorID, account, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteAccountUser provides a mock function with given fields: ctx, createAccountUser, createdAt
func (_m *MockDriver) WriteAccountUser(ctx context.Context, createAccountUser types.CreateAccountUserAccess, createdAt time.Time) (types.UserID, error) {
	ret := _m.Called(ctx, createAccountUser, createdAt)

	var r0 types.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.CreateAccountUserAccess, time.Time) (types.UserID, error)); ok {
		return rf(ctx, createAccountUser, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.CreateAccountUserAccess, time.Time) types.UserID); ok {
		r0 = rf(ctx, createAccountUser, createdAt)
	} else {
		r0 = ret.Get(0).(types.UserID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.CreateAccountUserAccess, time.Time) error); ok {
		r1 = rf(ctx, createAccountUser, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteBlockedContract provides a mock function with given fields: ctx, blockedAddress, createdAt
func (_m *MockDriver) WriteBlockedContract(ctx context.Context, blockedAddress types.BlockedAddress, createdAt time.Time) error {
	ret := _m.Called(ctx, blockedAddress, createdAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockedAddress, time.Time) error); ok {
		r0 = rf(ctx, blockedAddress, createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteChain provides a mock function with given fields: ctx, chain, createdAt
func (_m *MockDriver) WriteChain(ctx context.Context, chain types.Chain, createdAt time.Time) (*types.Chain, error) {
	ret := _m.Called(ctx, chain, createdAt)

	var r0 *types.Chain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Chain, time.Time) (*types.Chain, error)); ok {
		return rf(ctx, chain, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.Chain, time.Time) *types.Chain); ok {
		r0 = rf(ctx, chain, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Chain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.Chain, time.Time) error); ok {
		r1 = rf(ctx, chain, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteChainAndGigastakeApps provides a mock function with given fields: ctx, input, createdAt
func (_m *MockDriver) WriteChainAndGigastakeApps(ctx context.Context, input types.NewChainInput, createdAt time.Time) (*types.NewChainInput, error) {
	ret := _m.Called(ctx, input, createdAt)

	var r0 *types.NewChainInput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NewChainInput, time.Time) (*types.NewChainInput, error)); ok {
		return rf(ctx, input, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.NewChainInput, time.Time) *types.NewChainInput); ok {
		r0 = rf(ctx, input, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NewChainInput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.NewChainInput, time.Time) error); ok {
		r1 = rf(ctx, input, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteGigastakeApp provides a mock function with given fields: ctx, gigastakeApp, createdAt
func (_m *MockDriver) WriteGigastakeApp(ctx context.Context, gigastakeApp types.GigastakeApp, createdAt time.Time) (*types.GigastakeApp, error) {
	ret := _m.Called(ctx, gigastakeApp, createdAt)

	var r0 *types.GigastakeApp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.GigastakeApp, time.Time) (*types.GigastakeApp, error)); ok {
		return rf(ctx, gigastakeApp, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.GigastakeApp, time.Time) *types.GigastakeApp); ok {
		r0 = rf(ctx, gigastakeApp, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.GigastakeApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.GigastakeApp, time.Time) error); ok {
		r1 = rf(ctx, gigastakeApp, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WritePortalApp provides a mock function with given fields: ctx, portalApp, aat, createdAt
func (_m *MockDriver) WritePortalApp(ctx context.Context, portalApp types.PortalApp, aat types.AAT, createdAt time.Time) (*types.PortalApp, error) {
	ret := _m.Called(ctx, portalApp, aat, createdAt)

	var r0 *types.PortalApp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalApp, types.AAT, time.Time) (*types.PortalApp, error)); ok {
		return rf(ctx, portalApp, aat, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.PortalApp, types.AAT, time.Time) *types.PortalApp); ok {
		r0 = rf(ctx, portalApp, aat, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.PortalApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.PortalApp, types.AAT, time.Time) error); ok {
		r1 = rf(ctx, portalApp, aat, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteUserNewSignUp provides a mock function with given fields: ctx, user, createdAt
func (_m *MockDriver) WriteUserNewSignUp(ctx context.Context, user types.CreateUser, createdAt time.Time) (*types.User, types.AccountID, error) {
	ret := _m.Called(ctx, user, createdAt)

	var r0 *types.User
	var r1 types.AccountID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.CreateUser, time.Time) (*types.User, types.AccountID, error)); ok {
		return rf(ctx, user, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.CreateUser, time.Time) *types.User); ok {
		r0 = rf(ctx, user, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.CreateUser, time.Time) types.AccountID); ok {
		r1 = rf(ctx, user, createdAt)
	} else {
		r1 = ret.Get(1).(types.AccountID)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.CreateUser, time.Time) error); ok {
		r2 = rf(ctx, user, createdAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
